src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This is the Dealer&apos;s code</description>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACM_Entitlement_Settings__c.object
<CustomObject>
    <fields>
        <fullName>ACM_Duration_Unit__c</fullName>
        <label>Complimentary Maintenance Duration Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACM_Duration__c</fullName>
        <label>Complimentary Maintenance Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACM_KM_Limit__c</fullName>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <label>Main Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>ACM Entitlements Settings</relationshipLabel>
        <relationshipName>ACM_Entitlements_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <label>Sub Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>ACM Entitlement Settings</label>
    <nameField>
        <label>ACM Entitlement Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACM Entitlements Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <description>Main symbols being extended for complementary maintenance</description>
        <label>Main Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <description>Sub symbols being extended for complementary maintenance</description>
        <label>Sub Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Entitlement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Complimentary Maintenance Entitlement record that is used to create this claim</description>
        <label>Entitlement</label>
        <referenceTo>Entitlement__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MileageIn__c</fullName>
        <description>USED ONLY FOR CODE. Since we can&apos;t create a formula field for ServiceHistorys, we need this field to compare if the mileage is within the KM Limit</description>
        <label>MileageIn</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN/Serial #</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>ACM_Entitlement_Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACM Entitlement Settings</label>
        <referenceTo>ACM_Entitlement_Settings__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;A&quot;)) , &quot;A; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;B&quot;)) , &quot;B; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN/Serial #</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entitlement</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Entitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIN__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <formula>Dealer__r.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <formula>VIN_Serial_Number__r.Product__r.Model_Group__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>VIN_Serial_Number__r.Product__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeemed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PIN</label>
    <nameField>
        <label>PIN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is populated by ODS batch delta loads.</description>
    <fields>
        <fullName>MDL_YR_CD__c</fullName>
        <description>MDL_YR_CD
Model Year + Model Code to provide a unique identifier for the external system that is loading.</description>
        <externalId>true</externalId>
        <label>MDL YR CD</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <label>Model Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Regional_Pricing_Model__c.object
<CustomObject>
    <description>CRM Analysts maintain a regionalized pricing list based on maintenance symbols in order to display and view accurate claim pricing based on dealer’s regions and zones.</description>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Product__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Regional_Pricing_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Regionalized Pricing Entry</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Regionalized Pricing Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regionalized Pricing Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceHistorys__x.object
<CustomObject>
    <description>ServiceHistorys</description>
    <externalDataSource>ODS_Data</externalDataSource>
    <externalName>ServiceHistorys</externalName>
    <fields>
        <fullName>MileageIn__c</fullName>
        <description>MileageIn</description>
        <externalDeveloperName>MileageIn</externalDeveloperName>
        <label>Mileage In</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoNum__c</fullName>
        <description>RoNum</description>
        <externalDeveloperName>RoNum</externalDeveloperName>
        <label>Repair Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoVin__c</fullName>
        <description>RoVin</description>
        <externalDeveloperName>RoVin</externalDeveloperName>
        <label>RoVin</label>
        <length>255</length>
        <referenceTargetField>VIN__c.ProductSerialNumber__c</referenceTargetField>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>ServiceHistorys</relationshipLabel>
        <relationshipName>ServiceHistorys</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Service History</label>
    <pluralLabel>Service History</pluralLabel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>Model_Group__c</fullName>
        <formula>Product__r.Model_Group__c</formula>
        <label>Model Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Product__r.Model_Year__c</formula>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>VIN</relationshipLabel>
        <relationshipName>VIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_ClaimSubmissionControllerTest.cls
@isTest
private class H_ClaimSubmissionControllerTest {
	
	private static final Id ACM_RT = Schema.SObjectType.Entitlement__c.getRecordTypeInfosByName().get('Acura Complimentary Maintenance').getRecordTypeId();

	private static Account acc;
	private static Contact con;
	private static User portalUser;
	private static Campaign cam;
	private static PIN__c p;
	private static VIN__c v;
	private static Product__c prod;
	private static ServiceHistorys__x shx;
	private static Entitlement__c entitlement;
	private static ACM_Entitlement_Settings__c acmEntitlements;

	private static void setupTestValues() {

		Id pId = [select id from profile where name='Dealer Community User'].id;

		//Create an Account
		acc = new Account(Name = 'MS',
							Dealer_Code__c = '2008');
		insert acc;

		//create Contact
		con = new Contact(FirstName = 'MS',
							LastName = 'MS',
							AccountId = acc.Id);
		insert con;

		//Create User
		portalUser = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
                ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

		insert portalUser;

		//Create a campaign;
		cam = new Campaign(Name = 'Test Campaign 123',
							IsActive = true,
							Status = 'In Progress',
							StartDate = Date.today(),
							EndDate = Date.today().addDays(1));
		insert cam;

		// Create a PIN
		p = new PIN__c(Name = 'pin123',
						  Campaign__c = cam.Id,
						  Status__c = 'Active');
		insert p;

		prod = new Product__c(Model_Group__c = 'RL', MDL_YR_CD__c = 'RL2005', Model_Year__c = '2005');
		insert prod;

		v = new VIN__c(ProductSerialNumber__c = 'vin123', Product__c = prod.Id);
		insert v;

		//Create RO
		shx = new ServiceHistorys__x(RoVin__c = v.Id, RoNum__c = 'ro123', MileageIn__c = '190000');
	//	Database.insertImmediate(shx);

		acmEntitlements = new ACM_Entitlement_Settings__c();
     	acmEntitlements.Name = 'RL 2010';
     	acmEntitlements.ACM_Duration__c = 1;
     	acmEntitlements.ACM_Duration_Unit__c = 'Years';
     	acmEntitlements.ACM_KM_Limit__c = 900000;
     	acmEntitlements.Main_Symbols__c = 'A;B';
     	acmEntitlements.Sub_Symbols__c = '1;2;3;4;5';

     	insert acmEntitlements;
		entitlement = new Entitlement__c(VIN__c = v.Id, RecordTypeId = ACM_RT, ACM_Entitlement_Settings__c = acmEntitlements.Id);
		insert entitlement;

		Regionalized_Grouping__c rg = new Regionalized_Grouping__c(Name='AZ-Dlr 2008');

		insert rg;

		List<Regional_Pricing_Model__c> regionalPricingModelsList = new List<Regional_Pricing_Model__c>();

		Regional_Pricing_Model__c r1 = new Regional_Pricing_Model__c(Product__c = prod.Id, 
																		Symbol_Description__c = 'test',
																		Symbol__c = 'A',
																		Regionalized_Grouping__c = rg.Id,
																		Price__c = 10.00);
		regionalPricingModelsList.add(r1);
		
		Regional_Pricing_Model__c r2 = new Regional_Pricing_Model__c(Product__c = prod.Id, 
																		Symbol_Description__c = 'test',
																		Symbol__c = 'B',
																		Regionalized_Grouping__c = rg.Id,
																		Price__c = 20.00);
		regionalPricingModelsList.add(r2);
		Regional_Pricing_Model__c r3 = new Regional_Pricing_Model__c(Product__c = prod.Id, 
																		Symbol_Description__c = 'test',
																		Symbol__c = '1',
																		Regionalized_Grouping__c = rg.Id,
																		Price__c = 30.00);
		regionalPricingModelsList.add(r3);
		Regional_Pricing_Model__c r4 = new Regional_Pricing_Model__c(Product__c = prod.Id, 
																		Symbol_Description__c = 'test',
																		Symbol__c = '2',
																		Regionalized_Grouping__c = rg.Id,
																		Price__c = 30.00);
		
		regionalPricingModelsList.add(r4);
		Regional_Pricing_Model__c r5 = new Regional_Pricing_Model__c(Product__c = prod.Id, 
																		Symbol_Description__c = 'test',
																		Symbol__c = '3',
																		Regionalized_Grouping__c = rg.Id,
																		Price__c = 30.00);
		regionalPricingModelsList.add(r5);

		insert regionalPricingModelsList;



	}


	@isTest
	private static void updateLanguage_Test() {
		setupTestValues();

		Test.startTest();

		system.runAs(portalUser) {
           H_ClaimSubmissionController ctlr = new H_ClaimSubmissionController(); 
           ctlr.updateLanguage();

        }
		Test.stopTest();
		portalUser = [SELECT Id, LanguageLocaleKey FROM User WHERE Id =: portalUser.Id LIMIT 1];
		System.assert(portalUser.LanguageLocaleKey == 'fr', 'Portal User\'s Language updated form english to french');

	}

	@isTest
	private static void submitClaimValid_Test() {
		setupTestValues();

		Test.startTest();
	


		system.runAs(portalUser) {
           	H_ClaimSubmissionController.mockedServiceHistorys.add(shx);
			H_ClaimSubmissionController ctlr = new H_ClaimSubmissionController(); 
        	
           	ctlr.getMainSymbols();
           	ctlr.getSubSymbols();

           	ctlr.vinCode = 'vin123';
           	ctlr.roNumber = 'ro123';
           	//ctlr.model = 'RL';
           	ctlr.selectedMainSymbol = 'A';
           	ctlr.selected1stSubSymbol = '1';
           	ctlr.selected2ndSubSymbol = '2';
           	ctlr.selected3rdSubSymbol = '3';

           	ctlr.submitClaim();
           	ctlr.confirmClaim();

        }
		Test.stopTest();
		List<Claim__c> claim = [SELECT Id, X1st_Sub_Symbol__c, X2nd_Sub_Symbol__c, X3rd_Sub_Symbol__c, Main_Symbol__c, Model__c, Price_of_1st_Sub_Symbol__c,
									Price_of_2nd_Sub_Symbol__c, Price_of_3rd_Sub_Symbol__c, Price_of_Main_Symbol__c, Valid_Date__c, Valid_KM_Limit__c, VIN__c
									FROM Claim__c];

		System.assert(claim.size() == 1, '1 claim created');


	}

	@isTest
	private static void alreadySubmittedClaim_Test() {
		setupTestValues();
		
		//Create an existing Claim
		Claim__c claim = new Claim__c(X1st_Sub_Symbol__c = '1', 
									X2nd_Sub_Symbol__c = '2',
									X3rd_Sub_Symbol__c = '3',
									Main_Symbol__c = 'A',
									Model__c = 'RL',
									Price_of_1st_Sub_Symbol__c = 30.00,
									Price_of_2nd_Sub_Symbol__c = 30.00,
									Price_of_3rd_Sub_Symbol__c = 30.00,
									Price_of_Main_Symbol__c = 10.00,
									MileageIn__c = '123',
									VIN__c = v.Id,
									Entitlement__c = entitlement.Id);
		insert claim;

		Test.startTest();

		system.runAs(portalUser) {
           	H_ClaimSubmissionController.mockedServiceHistorys.add(shx);
			H_ClaimSubmissionController ctlr = new H_ClaimSubmissionController(); 
        	
           	ctlr.getMainSymbols();
           	ctlr.getSubSymbols();

           	ctlr.vinCode = 'vin123';
           	ctlr.roNumber = 'ro123';
           	//ctlr.model = 'RL';
           	ctlr.selectedMainSymbol = 'A';
           	ctlr.selected1stSubSymbol = '1';
           	ctlr.selected2ndSubSymbol = '2';
           	ctlr.selected3rdSubSymbol = '3';

           	ctlr.submitClaim();


        }
		Test.stopTest();

		List<Claim__c> claims= [SELECT Id, X1st_Sub_Symbol__c, X2nd_Sub_Symbol__c, X3rd_Sub_Symbol__c, Main_Symbol__c, Model__c, Price_of_1st_Sub_Symbol__c,
									Price_of_2nd_Sub_Symbol__c, Price_of_3rd_Sub_Symbol__c, Price_of_Main_Symbol__c, Valid_Date__c, Valid_KM_Limit__c, VIN__c
									FROM Claim__c];

		System.assert(claims.size() == 1, 'There is already a claim on the RO, another claim cannot be inserted');


	}

	@isTest
	private static void testButtons() {
		setupTestValues();

		Test.setCurrentPage(Page.H_ClaimSubmission);

		Test.startTest();

		system.runAs(portalUser) {
           	
        	H_ClaimSubmissionController.mockedServiceHistorys.add(shx);
			H_ClaimSubmissionController ctlr = new H_ClaimSubmissionController(); 

           	ctlr.getMainSymbols();
           	ctlr.getSubSymbols();

           	ctlr.vinCode = 'vin123';
           	ctlr.roNumber = 'ro123';
           	//ctlr.model = 'RL';
           	ctlr.selectedMainSymbol = 'A';
           	ctlr.selected1stSubSymbol = '1';
           	ctlr.selected2ndSubSymbol = '2';
           	ctlr.selected3rdSubSymbol = '3';

           	ctlr.submitClaim();

           	ctlr.goBack();
           	ctlr.refreshPage();

        }
		Test.stopTest();

	}
}