src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This is the Dealer&apos;s code</description>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Complimentary_Maintenance_Duration_Unit__c</fullName>
        <label>Complimentary Maintenance Duration Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_Duration__c</fullName>
        <description>Duration of complementary  maintenance entitlement</description>
        <label>Complimentary Maintenance Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_KM_Limit__c</fullName>
        <description>Kilometer limit of complementary maintenance entitlement</description>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <description>Main symbols being extended for complementary maintenance</description>
        <label>Main Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <description>Sub symbols being extended for complementary maintenance</description>
        <label>Sub Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_KM_Limit__c</fullName>
        <formula>IF(Campaign__c == NULL,ACM_Entitlement_Settings__r.ACM_KM_Limit__c ,Campaign__r.Complimentary_Maintenance_KM_Limit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;A&quot;)) , &quot;A; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;B&quot;)) , &quot;B; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;1&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;1&quot;)), &quot;1; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;2&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;2&quot;)), &quot;2; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;3&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;3&quot;)), &quot;3; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;4&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;4&quot;)), &quot;4; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;5&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;5&quot;)), &quot;5; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;6&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;6&quot;)), &quot;6; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN/Serial #</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entitlement</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Entitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIN__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <formula>Dealer__r.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeemed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VIN_Serial_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PIN</label>
    <nameField>
        <label>PIN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Retail_Process_Date__c</fullName>
        <label>Retail Process Date</label>
        <type>Date</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_PINSubmissionControllerTest.cls
@isTest
private class H_PINSubmissionControllerTest {
	
	private static Account acc;
	private static Contact con;
	private static User portalUser;
	private static Campaign cam;
	private static PIN__c p;
	private static VIN__c v;

	private final static Id ACM_RT = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Acura Complimentary Maintenance').getRecordTypeId();


	private static void setupTestValues() {
		Id pId = [select id from profile where name='Dealer Community User'].id;

		//Create an Account
		acc = new Account(Name = 'MS',
							Dealer_Code__c = 'dd123');

		insert acc;

		//create Contact
		con = new Contact(FirstName = 'MS',
							LastName = 'MS',
							AccountId = acc.Id);
		insert con;

		//Create User
		portalUser = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
                ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

		insert portalUser;

		//Create a campaign;
		cam = new Campaign(Name = 'Test Campaign 123',
							IsActive = true,
							Status = 'In Progress',
							StartDate = Date.today(),
							EndDate = Date.today().addDays(1),
							RecordTypeId = ACM_RT,
							Complimentary_Maintenance_KM_Limit__c = 9000000,
							Complimentary_Maintenance_Duration__c = 1,
							Complimentary_Maintenance_Duration_Unit__c = 'Years',
							Main_Symbols__c = 'A;B',
							Sub_Symbols__c = '1;2;3;4;5');
		insert cam;

		// Create a PIN
		p = new PIN__c(Name = 'pin123',
						  Campaign__c = cam.Id,
						  Status__c = 'Active');
		insert p;

		v = new VIN__c(ProductSerialNumber__c = 'vin123', Retail_Process_Date__c = Date.today().addDays(-3));
		insert v;

	}

	@isTest
	private static void test_update_language() {
		setupTestValues();

		Test.startTest();

		system.runAs(portalUser) {
           H_PINSubmissionController ctlr = new H_PINSubmissionController(); 
           ctlr.updateLanguage();

        }
		Test.stopTest();
		portalUser = [SELECT Id, LanguageLocaleKey FROM User WHERE Id =: portalUser.Id LIMIT 1];
		System.assert(portalUser.LanguageLocaleKey == 'fr', 'Portal User\'s Language updated form english to french');

	}


	@isTest 
	private static void test_verify_redeemed_pin() {
		setupTestValues();
		p.Status__c = 'Redeemed';

		update p;
		H_PINSubmissionController ctlr;

		Test.startTest();

		system.runAs(portalUser) {
			ctlr = new H_PINSubmissionController();
			ctlr.pinCode = p.Name;
			ctlr.verifyPIN();
		}
		Test.stopTest();

		System.assert(ctlr.invalidType == 'Redeemed', 'When a Redeemed PIN is verified, the invalidType is set as REDEEMED.');
	}
	
	@isTest 
	private static void test_verify_expired_pin() {
		setupTestValues();
		p.Status__c = 'Expired';

		update p;
		H_PINSubmissionController ctlr;

		Test.startTest();
		system.runAs(portalUser) {
			ctlr = new H_PINSubmissionController();
			ctlr.pinCode = p.Name;
			ctlr.verifyPIN();
			Test.stopTest();
		}

		System.assert(ctlr.invalidType == 'Expired', 'When an Expired PIN is verified, the invalidType is set as EXPIRED.');
	}

	@isTest 
	private static void test_verify_active_pin() {
		setupTestValues();

		Test.startTest();
		H_PINSubmissionController ctlr = new H_PINSubmissionController();
		ctlr.pinCode = p.Name;
		ctlr.verifyPIN();
		Test.stopTest();

		System.assert(ctlr.invalidType == 'Active', 'When an active PIN is verified, the invalidType is set as ACTIVE.');
	}

	@isTest 
	private static void test_verify_invalid_pin() {
		setupTestValues();

		Test.startTest();
		H_PINSubmissionController ctlr = new H_PINSubmissionController();
		ctlr.pinCode = 'tsdfss';
		ctlr.verifyPIN();
		Test.stopTest();

		System.assert(ctlr.invalidType == 'Invalid', 'When an invalid PIN is verified, the invalidType is set as INVALID.');
	}

	@isTest 
	private static void test_submit_active_pin() {
		setupTestValues();

		Test.startTest();
		H_PINSubmissionController ctlr = new H_PINSubmissionController();
		ctlr.pinCode = p.Name;
		ctlr.vinCode = v.ProductSerialNumber__c;
		ctlr.dealerCode = acc.Dealer_Code__c;
		ctlr.submitPIN();

		Test.stopTest();

		p = [SELECT Id, VIN_Serial_Number__c, Status__c FROM PIN__c where ID =: p.Id];
		List<Entitlement__c> eList = [SELECT Id from Entitlement__c WHERE VIN__c =: p.VIN_Serial_Number__c LIMIT 1];

		System.assert(ctlr.invalidType == 'Submitted', 'When an invalid PIN is submmited, the invalidType is set as Submitted.');
		System.assert(p.Status__c == 'Redeemed', 'The PIN is updated from Active to Redeemed');
		System.assert(eList.size() > 0, 'An entitlement record was created.');
	}

	@isTest 
	private static void test_submit_null_pin_null_vin() {
		setupTestValues();

		Test.startTest();
		H_PINSubmissionController ctlr = new H_PINSubmissionController();
		ctlr.pinCode = null;
		ctlr.vinCode = null;
		ctlr.submitPIN();
		Test.stopTest();

		System.assert(ctlr.invalidType == 'Invalid', 'When an invalid PIN is verified, the invalidType is set as INVALID.');
	}


	
}