src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This is the Dealer&apos;s code</description>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ErrorLog__c.object
<CustomObject>
    <description>Stores the Error Log of the failed records</description>
    <label>ErrorLog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIN__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <formula>Dealer__r.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pin_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Pin Code</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeemed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PIN</label>
    <nameField>
        <label>PIN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_GeneratePINsTest.cls
@isTest
private class H_GeneratePINsTest {
	
	private static Account acc;
	private static Contact con;
	private static Campaign cam;
	

	private static void setupTestValues() {

		//Create an Account
		acc = new Account(Name = 'MS',
							Dealer_Code__c = '2008');
		insert acc;

		//create Contact
		con = new Contact(FirstName = 'MS',
							LastName = 'MS',
							AccountId = acc.Id);
		insert con;


		//Create a campaign;
		cam = new Campaign(Name = 'Test Campaign 123',
							IsActive = true,
							Status = 'In Progress',
							StartDate = Date.today(),
							EndDate = Date.today().addDays(1));
		insert cam;

		CampaignMember cm = new CampaignMember(ContactId = con.Id, 
												CampaignId = cam.Id);

		insert cm;
	}

	@isTest
	private static void executeGeneratePINsButton_Test() {
		setupTestValues();

		Test.startTest();

		H_GeneratePINs.executeGeneratePINsBatch(cam.Id, 3);
		Test.stopTest();
		
		List<PIN__c> pinsInserted = [SELECT Id FROM PIN__c];
		System.assert(pinsInserted.size() == 3, '3 pins inserted per contact.');

	}

	@isTest
	private static void logErrors_Test() {
		setupTestValues();

		Test.startTest();

		List<PIN__c> pinsToCreate = new List<PIN__c>();

		// Pretend to insert pins where the Pin Code is the same value
		for(Integer i = 0; i < 2; i++) {
			
			PIN__c pin = new PIN__c();
			pin.Name = 'pin123';
			pin.Pin_Code__c = 'pin123';
			pin.Campaign__c = cam.Id;
			pin.Customer__c = con.Id; 
			pin.Status__c = 'Active';
			
			
			pinsToCreate.add(pin);
			
		}

		Database.SaveResult[] srList = Database.insert(pinsToCreate, false);

		insert H_GeneratePINs.createErrorLogs(srList, 'Test', 'test', 'test', 'Test', 'Test' , pinsToCreate);

		Test.stopTest();

		List<ErrorLog__c> errorLogs = [SELECT Id FROM ErrorLog__c];
		System.assert(errorLogs.size() > 0, '1 error log inserted because a duplicate pincode pin record cannot be inserted');
	}



}