src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This is the Dealer&apos;s code</description>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Main_Symbol__c</fullName>
        <label>Main Symbol</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MileageIn__c</fullName>
        <description>USED ONLY FOR CODE. Since we can&apos;t create a formula field for ServiceHistorys, we need this field to compare if the mileage is within the KM Limit</description>
        <label>MileageIn</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_of_1st_Sub_Symbol__c</fullName>
        <description>Cost associated with selected 1st sub symbol as calculated from the regionalized pricing model</description>
        <label>Price of 1st Sub Symbol</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_of_2nd_Sub_Symbol__c</fullName>
        <description>Cost associated with selected 2nd sub symbol as calculated from the regionalized pricing model</description>
        <label>Price of 2nd Sub Symbol</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_of_3rd_Sub_Symbol__c</fullName>
        <description>Cost associated with selected 3rd sub symbol as calculated from the regionalized pricing model</description>
        <label>Price of 3rd Sub Symbol</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_of_Main_Symbol__c</fullName>
        <description>Cost associated with selected main symbol as calculated from the regionalized pricing model</description>
        <label>Price of Main Symbol</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN/Serial #</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1st_Sub_Symbol__c</fullName>
        <label>1st Sub Symbol</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X2nd_Sub_Symbol__c</fullName>
        <label>2nd Sub Symbol</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X3rd_Sub_Symbol__c</fullName>
        <label>3rd Sub Symbol</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is populated by ODS batch delta loads.</description>
    <fields>
        <fullName>MDL_YR_CD__c</fullName>
        <description>MDL_YR_CD
Model Year + Model Code to provide a unique identifier for the external system that is loading.</description>
        <externalId>true</externalId>
        <label>MDL YR CD</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <label>Model Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceHistorys__x.object
<CustomObject>
    <description>ServiceHistorys</description>
    <externalDataSource>ODS_Data</externalDataSource>
    <externalName>ServiceHistorys</externalName>
    <fields>
        <fullName>MileageIn__c</fullName>
        <description>MileageIn</description>
        <externalDeveloperName>MileageIn</externalDeveloperName>
        <label>Mileage In</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoNum__c</fullName>
        <description>RoNum</description>
        <externalDeveloperName>RoNum</externalDeveloperName>
        <label>Repair Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoVin__c</fullName>
        <description>RoVin</description>
        <externalDeveloperName>RoVin</externalDeveloperName>
        <label>RoVin</label>
        <length>255</length>
        <referenceTargetField>VIN__c.ProductSerialNumber__c</referenceTargetField>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>ServiceHistorys</relationshipLabel>
        <relationshipName>ServiceHistorys</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Service History</label>
    <pluralLabel>Service History</pluralLabel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>Model_Group__c</fullName>
        <formula>Product__r.Model_Group__c</formula>
        <label>Model Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Product__r.Model_Year__c</formula>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>VIN</relationshipLabel>
        <relationshipName>VIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_ClaimHelperTest.cls
@isTest
private class H_ClaimHelperTest {

	@isTest
	private static void testManualShareRead_oneRecord(){

		List<Contact> contactsList = new List<Contact>();
		List<User> portalUsersList = new List<User>();

		Id pId = [select id from profile where name='Dealer Community User'].id;

		//Create an Account
		Account acc = new Account(Name = 'MS',
								Dealer_Code__c = '2008');
		insert acc;

		//create Contact
		Contact con = new Contact(FirstName = 'MS',
									LastName = 'MS',
									AccountId = acc.Id);
		contactsList.add(con);

		Contact con2 = new Contact(FirstName = 'TS',
									LastName = 'TS',
									AccountId = acc.Id);
		contactsList.add(con2);

		insert contactsList;

		//Create User
		User portalUser = new User(alias = 'test123', email='test123@noemail.com',
					                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
					                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
					                ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

		portalUsersList.add(portalUser);

		User portalUser2 = new User(alias = 'te222', email='test1233333@noemail.com',
					                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
					                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
					                ContactId = con2.Id, timezonesidkey='America/Los_Angeles', username='tester232323@noemail.com');

		portalUsersList.add(portalUser2);

		insert portalUsersList;

		Product__c prod = new Product__c(Model_Group__c = 'RL', MDL_YR_CD__c = 'RL2005', Model_Year__c = '2005');
		insert prod;

		VIN__c v = new VIN__c(ProductSerialNumber__c = 'vin123', Product__c = prod.Id);
		insert v;

		//Create RO
		ServiceHistorys__x shx = new ServiceHistorys__x(RoVin__c = v.Id, RoNum__c = 'ro123', MileageIn__c = '190000');

   		List<Claim__c> claimsList = new List<Claim__c>();

   		Test.startTest();
   		
   		System.runAs(portalUser) {
   			//Create an existing Claim
   			Claim__c c = new Claim__c(X1st_Sub_Symbol__c = '1', 
									X2nd_Sub_Symbol__c = '2',
									X3rd_Sub_Symbol__c = '3',
									Main_Symbol__c = 'A',
									Model__c = 'RL',
									Price_of_1st_Sub_Symbol__c = 30.00,
									Price_of_2nd_Sub_Symbol__c = 30.00,
									Price_of_3rd_Sub_Symbol__c = 30.00,
									Price_of_Main_Symbol__c = 10.00,
									MileageIn__c = '123',
									VIN__c = v.Id);

			claimsList.add(c);

			insert claimsList;
   		}
   		
		Test.stopTest();

		claimsList = [SELECT Id FROM Claim__c WHERE Id IN: claimsList];

      	// Query job sharing records.
     	List<Claim__Share> claimShares = [SELECT Id, UserOrGroupId, AccessLevel, 
        RowCause FROM Claim__Share WHERE ParentId IN: claimsList];
      
      	// Test for only one manual share on job.
      	System.assertEquals(claimShares.size(), 2, 'Set the object\'s sharing model to Read.');

      	System.debug(claimShares);
      
	    // Test attributes of manual share.
	    //System.assertEquals(claimShares[0].AccessLevel, 'Read');
	    //System.assertEquals(claimShares[0].RowCause, 'Manual');
	    //System.assertEquals(claimShares[0].UserOrGroupId, user2Id);
      
        // Test invalid job Id.
        //delete j;   
   
        // Insert manual share for deleted job id. 
        //System.assertEquals(JobSharing.manualShareRead(j.Id, user2Id), false);
   }  

   @isTest
	private static void testManualShareRead_batchRecords(){

		List<Account> accsList = new List<Account>();
		List<Contact> contactsList = new List<Contact>();
		List<User> portalUsersList = new List<User>();

		Id pId = [select id from profile where name='Dealer Community User'].id;

		//Create an Account
		Account acc = new Account(Name = 'MS',
								Dealer_Code__c = '2008');
		accsList.add(acc);

		Account acc2 = new Account(Name = 'testMS',
									Dealer_Code__c = '2122');
		accsList.add(acc2);

		insert accsList;

		//create Contact
		Contact con = new Contact(FirstName = 'MS',
									LastName = 'MS',
									AccountId = acc.Id);
		contactsList.add(con);

		Contact con2 = new Contact(FirstName = 'TS',
									LastName = 'TS',
									AccountId = acc.Id);
		contactsList.add(con2);

		Contact con3 = new Contact(FirstName = 'RE',
									LastName = 'RE',
									AccountId = acc2.Id);

		contactsList.add(con3);

		Contact con4 = new Contact(FirstName = 'RE2',
									LastName = 'RE2',
									AccountId = acc2.Id);

		contactsList.add(con4);


		insert contactsList;

		//Create User
		User portalUser = new User(alias = 'test123', email='test123@noemail.com',
					                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
					                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
					                ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

		portalUsersList.add(portalUser);

		User portalUser2 = new User(alias = 'te222', email='test1233333@noemail.com',
					                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
					                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
					                ContactId = con2.Id, timezonesidkey='America/Los_Angeles', username='tester232323@noemail.com');

		portalUsersList.add(portalUser2);

		//Create User
		User portalUser3 = new User(alias = 'test133', email='teee33@noemail.com',
					                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
					                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
					                ContactId = con3.Id, timezonesidkey='America/Los_Angeles', username='teee33@noemail.com');

		portalUsersList.add(portalUser3);

		User portalUser4 = new User(alias = 'te422', email='test323@noemail.com',
					                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
					                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
					                ContactId = con4.Id, timezonesidkey='America/Los_Angeles', username='test323@noemail.com');

		portalUsersList.add(portalUser4);

		insert portalUsersList;


		Product__c prod = new Product__c(Model_Group__c = 'RL', MDL_YR_CD__c = 'RL2005', Model_Year__c = '2005');
		insert prod;

		List<VIN__c> vinsList = new List<VIN__c>();
		VIN__c v = new VIN__c(ProductSerialNumber__c = 'vin123', Product__c = prod.Id);
		vinsList.add(v);

		VIN__c v2 = new VIN__c(ProductSerialNumber__c = 'vin1231212', Product__c = prod.Id);
		vinsList.add(v2);

		insert vinsList;


		//Create RO
		ServiceHistorys__x shx = new ServiceHistorys__x(RoVin__c = v.Id, RoNum__c = 'ro123', MileageIn__c = '190000');

   		List<Claim__c> claimsList = new List<Claim__c>();

   		Test.startTest();
   		
   		System.runAs(portalUser) {
   			//Create an existing Claim
   			Claim__c c = new Claim__c(X1st_Sub_Symbol__c = '1', 
									X2nd_Sub_Symbol__c = '2',
									X3rd_Sub_Symbol__c = '3',
									Main_Symbol__c = 'A',
									Model__c = 'RL',
									Price_of_1st_Sub_Symbol__c = 30.00,
									Price_of_2nd_Sub_Symbol__c = 30.00,
									Price_of_3rd_Sub_Symbol__c = 30.00,
									Price_of_Main_Symbol__c = 10.00,
									MileageIn__c = '123',
									VIN__c = v.Id);

			claimsList.add(c);

			Claim__c c2 = new Claim__c(X1st_Sub_Symbol__c = '1', 
									X2nd_Sub_Symbol__c = '2',
									X3rd_Sub_Symbol__c = '3',
									Main_Symbol__c = 'A',
									Model__c = 'RL',
									Price_of_1st_Sub_Symbol__c = 30.00,
									Price_of_2nd_Sub_Symbol__c = 30.00,
									Price_of_3rd_Sub_Symbol__c = 30.00,
									Price_of_Main_Symbol__c = 10.00,
									MileageIn__c = '123',
									VIN__c = v2.Id);

			claimsList.add(c2);

			insert claimsList;	
   		
   		}
		Test.stopTest();

		claimsList = [SELECT Id FROM Claim__c WHERE Id IN: claimsList];

      	// Query job sharing records.
     	List<Claim__Share> claimShares = [SELECT Id, UserOrGroupId, AccessLevel, 
        RowCause FROM Claim__Share WHERE ParentId IN: claimsList];
      
      	// Test for only one manual share on job.
      	System.assertEquals(claimShares.size(), 4, 'Set the object\'s sharing model to Read.');

      	System.debug(claimShares);
      
	    // Test attributes of manual share.
	    //System.assertEquals(claimShares[0].AccessLevel, 'Read');
	    //System.assertEquals(claimShares[0].RowCause, 'Manual');
	    //System.assertEquals(claimShares[0].UserOrGroupId, user2Id);
      
        // Test invalid job Id.
        //delete j;   
   
        // Insert manual share for deleted job id. 
        //System.assertEquals(JobSharing.manualShareRead(j.Id, user2Id), false);
   }  
}