src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This is the Dealer&apos;s code</description>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACM_Entitlement_Settings__c.object
<CustomObject>
    <fields>
        <fullName>ACM_Duration_Unit__c</fullName>
        <label>Complimentary Maintenance Duration Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACM_Duration__c</fullName>
        <label>Complimentary Maintenance Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACM_KM_Limit__c</fullName>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <label>Main Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>ACM Entitlements Settings</relationshipLabel>
        <relationshipName>ACM_Entitlements_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <label>Sub Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>ACM Entitlement Settings</label>
    <nameField>
        <label>ACM Entitlement Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACM Entitlements Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Complimentary_Maintenance_Duration_Unit__c</fullName>
        <label>Complimentary Maintenance Duration Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_Duration__c</fullName>
        <description>Duration of complementary  maintenance entitlement</description>
        <label>Complimentary Maintenance Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_KM_Limit__c</fullName>
        <description>Kilometer limit of complementary maintenance entitlement</description>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <description>Main symbols being extended for complementary maintenance</description>
        <label>Main Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <description>Sub symbols being extended for complementary maintenance</description>
        <label>Sub Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>ACM_Entitlement_Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACM Entitlement Settings</label>
        <referenceTo>ACM_Entitlement_Settings__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_KM_Limit__c</fullName>
        <formula>IF(Campaign__c == NULL,ACM_Entitlement_Settings__r.ACM_KM_Limit__c ,Campaign__r.Complimentary_Maintenance_KM_Limit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Complimentary_Maintenance_Start_Date__c</fullName>
        <formula>VIN__r.Retail_Process_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Complimentary Maintenance Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;A&quot;)) , &quot;A; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;B&quot;)) , &quot;B; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;1&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;1&quot;)), &quot;1; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;2&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;2&quot;)), &quot;2; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;3&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;3&quot;)), &quot;3; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;4&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;4&quot;)), &quot;4; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;5&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;5&quot;)), &quot;5; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;6&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;6&quot;)), &quot;6; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN/Serial #</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entitlement</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Entitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIN__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <formula>Dealer__r.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <formula>VIN_Serial_Number__r.Product__r.Model_Group__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>VIN_Serial_Number__r.Product__r.Model_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeemed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PIN</label>
    <nameField>
        <label>PIN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is populated by ODS batch delta loads.</description>
    <fields>
        <fullName>MDL_YR_CD__c</fullName>
        <description>MDL_YR_CD
Model Year + Model Code to provide a unique identifier for the external system that is loading.</description>
        <externalId>true</externalId>
        <label>MDL YR CD</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <label>Model Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>Model_Group__c</fullName>
        <formula>Product__r.Model_Group__c</formula>
        <label>Model Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Product__r.Model_Year__c</formula>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>VIN</relationshipLabel>
        <relationshipName>VIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Process_Date__c</fullName>
        <label>Retail Process Date</label>
        <type>Date</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_VINTriggerHelperTest.cls
@isTest
private class H_VINTriggerHelperTest {
    private static Account acc;
    private static Contact con;
    private static User portalUser;
    private static Campaign cam;
    private static PIN__c p;
    private static VIN__c v;
    private static Product__c vinProduct;
    private static ACM_Entitlement_Settings__c acmEntitlements;

    private final static Id ACM_RT = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Acura Complimentary Maintenance').getRecordTypeId();


    private static void setupTestValues() {
        Id pId = [select id from profile where name='Dealer Community User'].id;

        //Create an Account
        acc = new Account(Name = 'MS',
                            Dealer_Code__c = 'dd123');

        insert acc;

        //create Contact
        con = new Contact(FirstName = 'MS',
                            LastName = 'MS',
                            AccountId = acc.Id);
        insert con;

        //Create User
        portalUser = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = pId, country='United States',IsActive =true,
                ContactId = con.Id, timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

        insert portalUser;

        //Create a campaign;
        cam = new Campaign(Name = 'Test Campaign 123',
                            IsActive = true,
                            Status = 'In Progress',
                            StartDate = Date.today(),
                            EndDate = Date.today().addDays(1),
                            RecordTypeId = ACM_RT,
                            Complimentary_Maintenance_KM_Limit__c = 9000000,
                            Complimentary_Maintenance_Duration__c = 1,
                            Complimentary_Maintenance_Duration_Unit__c = 'Years',
                            Main_Symbols__c = 'A;B',
                            Sub_Symbols__c = '1;2;3;4;5');
        insert cam;

        // Create a PIN
        p = new PIN__c(Name = 'pin123',
                          Campaign__c = cam.Id,
                          Status__c = 'Active');
        insert p;
        
        vinProduct = new Product__c(Model_Group__c = 'RL', Model_Year__c = '2010', MDL_YR_CD__c = 'RL2010');
        insert vinProduct;

        acmEntitlements = new ACM_Entitlement_Settings__c();
        acmEntitlements.Name = 'RL 2010';
        acmEntitlements.ACM_Duration__c = 1;
        acmEntitlements.ACM_Duration_Unit__c = 'Years';
        acmEntitlements.ACM_KM_Limit__c = 900000;
        acmEntitlements.Main_Symbols__c = 'A;B';
        acmEntitlements.Sub_Symbols__c = '1;2;3;4;5';
        acmEntitlements.Product__c = vinProduct.Id;

        insert acmEntitlements;

    }


    @isTest
    private static void test_insert_vin_with_entitlements() {
        setupTestValues();

        Test.startTest();

        v = new VIN__c(ProductSerialNumber__c = 'vin123', Retail_Process_Date__c = Date.today().addDays(-3), Product__c = vinProduct.Id);
        insert v;
        

        Test.stopTest();
        List<Entitlement__c> eList = [SELECT Id, Complimentary_Maintenance_Start_Date__c FROM Entitlement__c];
        System.assert(eList.size() > 0, 'Entitlement was inserted against the VIN');
        System.assert(eList[0].Complimentary_Maintenance_Start_Date__c == Date.today().addDays(-3), 'The Complimentary Maintenance Start Date is the same say as the Retail Process Date');


    }

}