src/objects/ACM_Entitlement_Settings__c.object
<CustomObject>
    <fields>
        <fullName>ACM_Duration_Unit__c</fullName>
        <label>Complimentary Maintenance Duration Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACM_Duration__c</fullName>
        <label>Complimentary Maintenance Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACM_KM_Limit__c</fullName>
        <label>Complimentary Maintenance KM Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deactivate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <label>Main Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>ACM Entitlements Settings</relationshipLabel>
        <relationshipName>ACM_Entitlements_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <label>Sub Symbols</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>ACM Entitlement Settings</label>
    <nameField>
        <label>ACM Entitlement Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACM Entitlements Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>ACM_Entitlement_Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACM Entitlement Settings</label>
        <referenceTo>ACM_Entitlement_Settings__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;A&quot;)) , &quot;A; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Main_Symbols__c  , &quot;A&quot;),INCLUDES(Campaign__r.Main_Symbols__c  , &quot;B&quot;)) , &quot;B; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Symbols__c</fullName>
        <formula>IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;1&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;1&quot;)), &quot;1; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;2&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;2&quot;)), &quot;2; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;3&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;3&quot;)), &quot;3; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;4&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;4&quot;)), &quot;4; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;5&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;5&quot;)), &quot;5; &quot;,&quot;&quot;)
&amp;
IF( IF(Campaign__c == NULL,INCLUDES(ACM_Entitlement_Settings__r.Sub_Symbols__c  , &quot;6&quot;),INCLUDES(Campaign__r.Sub_Symbols__c  , &quot;6&quot;)), &quot;6; &quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Symbols</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VIN/Serial #</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entitlement</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Entitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is populated by ODS batch delta loads.</description>
    <fields>
        <fullName>Air_Condition__c</fullName>
        <label>Air Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cylinders__c</fullName>
        <label>Cylinders</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Door_Type__c</fullName>
        <label>Door Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drive_Train__c</fullName>
        <label>Drive Train</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Immobilizer_Indicator__c</fullName>
        <label>Immobilizer Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Grade_Code__c</fullName>
        <label>Model Grade Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Group_Code__c</fullName>
        <label>Model Group Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <label>Model Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Motive_Power__c</fullName>
        <label>Motive Power</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>A   = Honda 
C   = Acura 
M  = Motorcycle 
P  = Power Equipment</description>
        <inlineHelpText>A   = Honda 
C   = Acura 
M  = Motorcycle 
P  = Power Equipment</inlineHelpText>
        <label>Product Line (ODS)</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Telematic_Flag__c</fullName>
        <label>Telematic Flag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transmission_Speed__c</fullName>
        <label>Transmission Speed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wheelbase__c</fullName>
        <label>Wheelbase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XMITN_Code__c</fullName>
        <label>XMITN Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>Air_Condition__c</fullName>
        <formula>Product__r.Air_Condition__c</formula>
        <label>Air Condition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cylinders__c</fullName>
        <formula>Product__r.Cylinders__c</formula>
        <label>Cylinders</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Door_Type__c</fullName>
        <formula>Product__r.Door_Type__c</formula>
        <label>Door Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drive_Train__c</fullName>
        <formula>Product__r.Drive_Train__c</formula>
        <label>Drive Train</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Immobilizer_Indicator__c</fullName>
        <formula>Product__r.Immobilizer_Indicator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Immobilizer Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Grade_Code__c</fullName>
        <formula>Product__r.Model_Grade_Code__c</formula>
        <label>Model Grade Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Group_Code__c</fullName>
        <formula>Product__r.Model_Group_Code__c</formula>
        <label>Model Group Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Group__c</fullName>
        <formula>Product__r.Model_Group__c</formula>
        <label>Model Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Product__r.Model_Year__c</formula>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Motive_Power__c</fullName>
        <formula>Product__r.Motive_Power__c</formula>
        <label>Motive Power</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLastUpdateDate__c</fullName>
        <label>ProductLastUpdateDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ProductLastUpdateUser__c</fullName>
        <label>ProductLastUpdateUser</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductValue__c</fullName>
        <description>MDM field that we are not displaying to the end users.</description>
        <label>ProductValue</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Product__r.Product_Line_frontend__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>VIN</relationshipLabel>
        <relationshipName>VIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Process_Date__c</fullName>
        <label>Retail Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Telematic_Flag__c</fullName>
        <formula>Product__r.Telematic_Flag__c</formula>
        <label>Telematic Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transmission_Speed__c</fullName>
        <formula>Product__r.Transmission_Speed__c</formula>
        <label>Transmission Speed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wheelbase__c</fullName>
        <formula>Product__r.Wheelbase__c</formula>
        <label>Wheelbase</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XMITN_Code__c</fullName>
        <formula>Product__r.XMITN_Code__c</formula>
        <label>XMITN Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isVINUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isVINUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_VINTriggerHelper.cls
/**
 *      @author       : Merisha Shim (Deloitte)
 *      @date         : 02/11/2016
 *      @description  : Helper class for H_VINTrigger Apex Trigger
 *      Modification Log:
 *      ------------------------------------------------------------------------------------------
 *           Developer               User story            Date                Description
 *      ------------------------------------------------------------------------------------------
 *          Merisha Shim (Deloitte)                        02/11/2016          Original Version
 */
public with sharing class H_VINTriggerHelper {

    private static final Id ACM_RT = Schema.SObjectType.Entitlement__c.getRecordTypeInfosByName().get('Acura Complimentary Maintenance').getRecordTypeId();


    /*
    * When a VIN is inserted, the system checks the “Complimentary Maintenance” custom settings for the VIN’s model group. If the model 
    * group exists in the custom settings, a Complimentary Maintenance record gets automatically created for the VIN.
    */
    public static void insertACMENtitlementBasedOnCustomSettings(List<VIN__c> newVINsList) {
        
        List<VIN__c> vinsToCreateEntitlementsList = new List<VIN__c>();
        List<Entitlement__c> entitlementsToCreate = new List<Entitlement__c>();
        Map<Id, Id> vinIdToProductId = new Map<Id, Id>();
        Map<Id, Id> productIdToACMSettingsId = new Map<Id, Id>();

        // Query for the Active entitlements in the system
        List<ACM_Entitlement_Settings__c> acmEntitlements = [SELECT Id, ACM_Duration__c, ACM_Duration_Unit__c, ACM_KM_Limit__c, Main_Symbols__c, 
                                                                Sub_Symbols__c, Product__c
                                                                FROM ACM_Entitlement_Settings__c
                                                                WHERE Deactivate__c != TRUE];

        for(ACM_Entitlement_Settings__c acm : acmEntitlements) {
            productIdToACMSettingsId.put(acm.Product__c, acm.Id);
        }


        if(!acmEntitlements.isEmpty()) {
            //Re-query the VINs so we can get lookup fields. 
            newVINsList = [SELECT Id, Air_Condition__c, Cylinders__c, Door_Type__c, Drive_Train__c, Immobilizer_Indicator__c,
                            isVINUpdated__c, Model_Grade_Code__c, Model_Group__c, Model_Group_Code__c, Model_Year__c,
                            Motive_Power__c, Product__c, ProductLastUpdateDate__c, ProductLastUpdateUser__c, Product_Line__c,
                            ProductValue__c, Telematic_Flag__c, Transmission_Speed__c, ProductSerialNumber__c, Wheelbase__c, 
                            XMITN_Code__c, Product__r.Model_Year__c, Retail_Process_Date__c, (SELECT Id FROM Entitlements__r)
                            FROM VIN__c
                            WHERE Id IN: newVINsList ];

            for(Integer i = 0; i < newVINsList.size(); i++) {
                if((newVINsList[i].Entitlements__r).isEmpty() && productIdToACMSettingsId.get(newVINsList[0].Product__c) != NULL) {
                    vinIdToProductId.put(newVINsList[i].Id, newVINsList[i].Product__c);
                   
                }
            }

            if(!vinIdToProductId.isEmpty()) {
                for(Id v : vinIdToProductId.keySet()){
                    
                    Entitlement__c entitlementToAdd = new Entitlement__c();
                    entitlementToAdd.RecordTypeId = ACM_RT;
                    entitlementToAdd.VIN__c = v;
                    entitlementToAdd.ACM_Entitlement_Settings__c = productIdToACMSettingsId.get(vinIdToProductId.get(v));
                    entitlementsToCreate.add(entitlementToAdd);

                }
            }

            if(!entitlementsToCreate.isEmpty()) {
                try {
                    insert entitlementsToCreate;
                } catch(Exception e) {
                    throw new H_VINTriggerHelperException(e.getMessage());
                }
                
            }
        }

        
    }

    public class H_VINTriggerHelperException extends Exception{}
}