src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>AddressLineOne__c</fullName>
        <encrypted>true</encrypted>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressUsageValue__c</fullName>
        <description>Primary residence is brought up to the contact.  All other types are not.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCOA Address</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encrypted>true</encrypted>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CountryValue__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States of America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Created_from_New_contact_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created from New contact Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProvinceStateValue__c</fullName>
        <label>Province / State</label>
        <picklist>
            <picklistValues>
                <fullName>AB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ZipPostalCode__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Please enter a Postal Code / Zip Code without any spaces.</inlineHelpText>
        <label>Postal / Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Addr-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HFS_Email__c</fullName>
        <label>HFS Email</label>
        <picklist>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YES</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <label>Organization Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContactMethod__c.object
<CustomObject>
    <fields>
        <fullName>ContactMethodValue__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>Telephone Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Methods</relationshipLabel>
        <relationshipName>Contact_Method</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Created_from_New_contact_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created from New contact Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReferenceNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Contact Method</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Contact Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Method</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/H_ContactInsertController.cls
/**
*      @author       : Piyush Rathor(Deloitte)
*      @date         : 08/01/2016
    @description  : Class for H_ContactInsert Visualforce Page and for custom contact creation
        Modification Log:
        ------------------------------------------------------------------------------------------
            Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
        Piyush Rathor                                   08/01/2016         Class for H_ContactInsert Visualforce Page and for custom contact creation
        Piyush Rathor                                   27/01/2016         Changes based on the comments on User Story
        Piyush Rathor                                   2/02/2016          Province State value picklist
        Piyush Rathor                                   8/02/2016          Future Method for Address and Contact Method Insertion
*/    
public with sharing class H_ContactInsertController {

    public contact contactRecord{get;set;}
    public string contactType{get;set;}
    public string selectedProvince{get;set;}
    public string selectedCountry{get;set;}
    
    public H_ContactInsertController(ApexPages.StandardController controller) {
        selectedProvince = '';
        selectedCountry = '';
        string recTypeVal = apexpages.currentpage().getparameters().get('RecordType');
        contactType = '';
        list<recordtype>lstRecordType = [select id,DeveloperName from recordtype where id =: recTypeVal and SobjectType = 'contact'];
        if(!lstRecordType.isEmpty())
        contactType = lstRecordType[0].DeveloperName;  
            
        contactRecord = (contact)controller.getRecord();
        //Id customerRecordTypeId = Schema.SObjectType.contact.getRecordTypeInfosByName().get(contactType).getRecordTypeId();
        //contactRecord.HFS_Email__c = 'YES';
        if(recTypeVal != null && recTypeVal != '')
        contactRecord.recordtypeId = recTypeVal;
        
    }
    
    public pagereference saveRec(){
        try{
            string errorMsg ='';
            boolean requiredFieldsFilled = false;
            boolean AddressFieldsFilled = false;
            /*
            if(contactRecord.mailingStreet != null && contactRecord.mailingStreet != '' ){
                requiredFieldsFilled = true;
            }
            else
            errorMsg = errorMsg+'Primary Street,';
            if(contactRecord.mailingcity != null && contactRecord.mailingcity != '' ){
                requiredFieldsFilled = true;
            }
            else
                errorMsg = errorMsg+' Primary City,';
            */
            if(selectedProvince != null && selectedProvince != ''){
                
                contactRecord.MailingState = selectedProvince;
            }
            else{
                errorMsg = errorMsg+' Primary State/Province,';
                AddressFieldsFilled = true;
            }
            if(selectedCountry != null && selectedCountry != ''){
                contactRecord.MailingCountry = selectedCountry;
            }
            else{
                errorMsg = errorMsg+' Primary Country,';
                AddressFieldsFilled = true;
            }
           
            if(AddressFieldsFilled && errorMsg != null && errorMsg != ''){
                errorMsg = errorMsg.substringBeforeLast(',');
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,errorMsg +' : You must enter a value'));
                return null;
            }
            else{
                requiredFieldsFilled = true;
            }
            if(contactRecord.Phone != null && contactRecord.Phone != ''){
                requiredFieldsFilled = true;
            }
            if(contactRecord.Email != null && contactRecord.Email != ''){
                requiredFieldsFilled = true;
            }
            if(!requiredFieldsFilled){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,label.Contact_Insert_Error1));
                return null;
            }
            if(contactRecord.OrganizationName__c != null && contactRecord.OrganizationName__c != ''){
                contactRecord.lastName = contactRecord.OrganizationName__c;
            }
            
            insert contactRecord;
            
            if(contactRecord.Id != null){
                insertRelatedRecords(contactRecord.Id);
            }
            
            pagereference pg = new pagereference('/'+contactRecord.Id);
            return pg;          
        }
        catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            return null;
        }
    }
    @future
    public static void insertRelatedRecords(Id contactId){
        list<contact>lstContact = [Select id,mailingStreet,mailingcity,MailingState,MailingPostalCode,mailingcountry,Phone,Email from contact where Id =: contactId];
        list<ContactMethod__c>lstConMethod = new List<ContactMethod__c>();
        
        if(!lstContact.isEmpty()){
            Address__c addressRecord = new Address__c();
            addressRecord.AddressLineOne__c = lstContact[0].mailingStreet;
            addressRecord.City__c = lstContact[0].mailingcity;
            addressRecord.ProvinceStateValue__c = lstContact[0].MailingState ;
            addressRecord.Contact__c = lstContact[0].Id;
            addressRecord.ZipPostalCode__c = lstContact[0].MailingPostalCode;
            addressRecord.CountryValue__c = lstContact[0].mailingcountry;
            addressRecord.AddressUsageValue__c = H_Constants.addressUsageVal;
            addressRecord.StartDate__c = system.now();
            addressRecord.Created_from_New_contact_Page__c = true;
            if(lstContact[0].Phone  != null){
                ContactMethod__c conMethod = new ContactMethod__c();
                conMethod.Contact__c = lstContact[0].Id;
                conMethod.ReferenceNumber__c = lstContact[0].Phone;
                conMethod.ContactMethodValue__c = H_Constants.contactMethodValuePhone;
                conMethod.ContactMethodUsageValue__c = H_Constants.contactMethodUsageValuePhone;
                conMethod.StartDate__c = system.now();
                conMethod.Created_from_New_contact_Page__c = true;
                lstConMethod.add(conMethod);
            }
            if(lstContact[0].Email != null &&  lstContact[0].Email != ''){
                ContactMethod__c conMethod1 = new ContactMethod__c();
                conMethod1.Contact__c = lstContact[0].Id;
                conMethod1.ReferenceNumber__c = lstContact[0].Email;
                conMethod1.ContactMethodValue__c = H_Constants.contactMethodValue;
                conMethod1.ContactMethodUsageValue__c = H_Constants.contactMethodUsageValue;
                conMethod1.StartDate__c = system.now();
                conMethod1.Created_from_New_contact_Page__c = true;
                lstConMethod.add(conMethod1);
            }
            try{
                insert addressRecord;
                
                if(!lstConMethod.isEmpty())
                    insert lstConMethod;
            }
            catch(exception e){
                H_Logger.error(e.getMessage(), 'H_ContactInsertController '+ ' : '+ 'Address Insert','ERROR');
            }
        }
    }
    
    public List<SelectOption>getProvince() {
        List<SelectOption> options = new List<SelectOption>();
        String provinceVal = H_Constants.provinceValue;
        options.add(new SelectOption('','--None--'));
        list<string>lstProvince = new list<string>();
        lstProvince = provinceVal.split(',');
        lstProvince.sort();
        for(string s : lstProvince){
            options.add(new SelectOption(s,s));
        }
        return options;
    }
    
    public List<SelectOption>getCountry() {
        List<SelectOption> options = new List<SelectOption>();
        String countryVal = H_Constants.countryValue;
        options.add(new SelectOption('','--None--'));
        options.add(new SelectOption('Canada','Canada'));
        options.add(new SelectOption('United States of America','United States of America'));       
        list<string>lstCountry = new list<string>();
        lstCountry = countryVal.split(',');
        lstCountry.sort();
        for(string s : lstCountry){
            if(!(s.containsIgnoreCase('Canada') || s.containsIgnoreCase('United States of America')))
            options.add(new SelectOption(s,s));
        }
        return options;
    }
    
    public pagereference cancelRec(){
        pagereference pg = new pagereference('/003/o');
        return pg;
    }
}