src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Addr-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ToBeDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is a flag to check if the contact needs to be deleted or not</description>
        <label>To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Customer or Business Customer</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer, Organization</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <description>Formula lookup to the UCID.  This is sent in the Workflow outbound message to MDM.</description>
        <formula>Contact__r.UCID__c</formula>
        <label>UCID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Role</label>
    <nameField>
        <displayFormat>Role-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_Delete_Contacts_test.cls
/**
*      @author       : Piyush Rathor(Deloitte)
*      @date         : 10/09/2015
        @description  : Test Class for H_Delete_Contacts_Schedule and H_Delete_Contacts_Batch class
        Modification Log:
        ------------------------------------------------------------------------------------------
            Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
           Piyush (Deloitte)                           06/10/2015           Original Version
*/
@istest
public class H_Delete_Contacts_test{
    //Test method to test scenarios to delete contact and related records
    static testMethod void  testContactDeletion(){
         //Test account Record
        Account objAccount = H_ParsingTestDataUtility.createAccount(1)[0];
        if(objAccount != null) 
        insert objAccount;
        system.assertnotEquals(objAccount.Id,null);
        
        //Test Contact Record
        list<Contact>lstContact = H_ParsingTestDataUtility.createContact(1);
        lstContact[0].UCID__c = '3444445310010135';
        lstContact[0].AccountId = objAccount.Id;
        lstContact[0].ToBeDeleted__c = true;
        lstContact[0].phone = '1234567890';
        lstContact[0].email = 'test@test.com';
        lstContact[0].mailingstreet = 'test';
        if(lstContact != null && !lstContact.isEmpty())
        insert lstContact;
        system.assertEquals(lstContact.size(),1);
        
        vin__c vinRecord = H_ParsingTestDataUtility.createVin();
        if(vinRecord != null)
        insert vinRecord;
        system.assertnotEquals(vinRecord.Id,null);
        
        if(lstContact != null && !lstContact.isEmpty()){
	        Customer_Role__c  custRoleRecord = H_ParsingTestDataUtility.createCustomerRole(lstContact[0].Id);
	        if(vinRecord != null)
	        custRoleRecord.vin__c = vinRecord.Id;
	        if(custRoleRecord != null)
	        insert custRoleRecord;
	        system.assertnotEquals(custRoleRecord.Id,null);
        }
        
        List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(1);
        if(lstContact != null && !lstContact.isEmpty())
        lstAddress[0].Contact__c = lstContact[0].Id;
        lstAddress[0].UCID__c = '3444445310010135';
        if(lstAddress != null && !lstAddress.isEmpty())
        insert lstAddress;
        system.assertEquals(lstAddress.size(),1);
        
        test.startTest();
            H_Delete_Contacts_Schedule contactDeleteSchedule = new H_Delete_Contacts_Schedule();
            String sch = '0 0 23 * * ?'; 
            system.schedule('Test Delete', sch, contactDeleteSchedule); 
        test.stopTest();
    }
}