src/objects/Address__c.object
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Addr-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ErrorLog__c.object
<CustomObject>
    <description>Stores the Error Log of the failed records</description>
    <fields>
        <fullName>Log_Level__c</fullName>
        <description>Stores the Severity of the Log</description>
        <label>Log Level</label>
        <picklist>
            <picklistValues>
                <fullName>TRACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEBUG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WARN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERROR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FATAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Stores the message</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notify_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether to notify to Admin or not</description>
        <label>Notify Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Stores the type of the Operation</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Territory Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DML Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webservice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Callouts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Async Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webservice (MDM) - Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webservice (MDM) - Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ErrorLog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_H_Logger.cls
/**
 *      @author       : Shilpa Menghani(Deloitte)
 *      @date         : 22/06/2015
        @description  : Test Class for H_Logger
        Modification Log:
        ------------------------------------------------------------------------------------------
                Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
                Shilpa (Deloitte)                              25/08/2015           Original Version
*/
@istest(seeAllData = false)
public class Test_H_Logger {

  static testMethod void testDoInsert(){
        try {
            List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(2);
            
            Test.startTest();
            ErrorLog__c log_obj=new ErrorLog__c(Message__c='testMessage',Log_Level__c='DEBUG',Type__c='Apex',Notify_Admin__c=true,Status_Code__c='testStatus');
            if(log_obj != null)
            insert log_obj;
            
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, 'This is a FATAL error');
            List<Database.SaveResult> results = H_DBFunctions.doInsert(lstAddress, 'H_LoggerTest', 'testCallingErrorFunctions', false); 
            
            H_Logger.notify=true;
            H_Logger.getDMLErrorMsg(results);
            H_Logger.error(results,'testOrigin','error xml','objType',null);
            H_Logger.log('message','level','statusCode','logtype');
            H_Logger.log('message','level','statusCode','logtype','error xml','objType',null,false); 
            H_Logger.error('message','statusCode','logtype','error xml','objType',null); 
            H_Logger.errorAsync('message','statusCode','logtype'); 
            H_Logger.warn('message','statusCode','logtype');
            H_Logger.debug('message','statusCode','logtype');
            H_Logger.trace('message','statusCode','logtype');
            H_Logger.addPageMessage(myMsg);
            H_Logger.getDMLSuccessMsg(results);
            H_Logger.errorAsync('msg','origin');
            H_Logger.info('message','statusCode','logtype');
            H_Logger.toString(log_obj);
            Test.stopTest();
        } 
        catch (DmlException e) { 
            System.assertEquals('Attempt to de-reference a null object', e.getDmlStatusCode(0));                                                           
        }
    }
    
    static testMethod void testDoUpsert2(){
        try {
            List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(2);
            
            Test.startTest();
            
            ErrorLog__c log_obj=new ErrorLog__c(Message__c='testMessage',Log_Level__c='DEBUG',Type__c='Apex',Notify_Admin__c=true,Status_Code__c='testStatus');
            if(log_obj != null)
            insert log_obj;
            
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, 'This is a FATAL error');
            List<Database.UpsertResult> results = H_DBFunctions.doUpsert(lstAddress, 'H_LoggerTest', 'testCallingErrorFunctions', false); 
            
            H_Logger.notify=true;
            H_Logger.getDMLErrorMsg(results);
            H_Logger.error(results,'testOrigin','error xml','objType',null);
            H_Logger.log('message','level','statusCode','logtype');
             H_Logger.log('message','level','statusCode','logtype','error xml','objType',null,false);
            H_Logger.error('message','statusCode','logtype','error xml','objType',null);
            H_Logger.errorAsync('message','statusCode','logtype');
            H_Logger.warn('message','statusCode','logtype');
            H_Logger.debug('message','statusCode','logtype');
            H_Logger.trace('message','statusCode','logtype');
            H_Logger.addPageMessage(myMsg);
            H_Logger.addPageMessage(ApexPages.Severity.FATAL,'my Error message');
            H_Logger.getDMLSuccessMsg(results);
            H_Logger.errorAsync('msg','origin');
            H_Logger.info('message','statusCode','logtype');
            H_Logger.toString(log_obj);
            
            Test.stopTest();
        } 
        catch (DmlException e) { 
            System.assertEquals('Attempt to de-reference a null object', e.getDmlStatusCode(0));                                                           
        }
    }

     static testMethod void testDoDelete(){
        try {
            List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(2);
            
            Test.startTest();
            
            ErrorLog__c log_obj=new ErrorLog__c(Message__c='testMessage',Log_Level__c='DEBUG',Type__c='Apex',Notify_Admin__c=true,Status_Code__c='testStatus');
            if(log_obj != null)
            insert log_obj;
            
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, 'This is a FATAL error');
            List<Database.SaveResult> results = H_DBFunctions.doInsert(lstAddress, 'H_LoggerTest', 'testCallingErrorFunctions', false); 
            List<Database.DeleteResult> resultPostDelete = H_DBFunctions.doDelete(lstAddress, 'H_LoggerTest', 'testCallingErrorFunctions', false); 
            
            H_Logger.notify=true;
            H_Logger.getDMLErrorMsg(resultPostDelete);
            H_Logger.error(results,'testOrigin','error xml','objType',null);
            H_Logger.log('message','level','statusCode','logtype');
            H_Logger.log('message','level','statusCode','logtype','error xml','objType',null,false); 
            H_Logger.error('message','statusCode','logtype');
            H_Logger.error('message','statusCode','logtype','error xml','objType',null);
            H_Logger.errorAsync('message','statusCode','logtype');
            H_Logger.warn('message','statusCode','logtype');
            H_Logger.debug('message','statusCode','logtype');
            H_Logger.trace('message','statusCode','logtype');
            H_Logger.addPageMessage(myMsg);
            H_Logger.getDMLSuccessMsg(resultPostDelete);
            H_Logger.errorAsync('msg','origin');
            H_Logger.info('message','statusCode','logtype');
            H_Logger.toString(log_obj);
            Test.stopTest();
        } 
        catch (DmlException e) { 
            System.assertEquals('Attempt to de-reference a null object', e.getDmlStatusCode(0));                                                           
        }
    }
    
}