src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>AddressUsageValue__c</fullName>
        <description>Primary residence is brought up to the contact.  All other types are not.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCOA Address</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CountryValue__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Addr-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_H_DBFunctions.cls
/**
 *      @author       : Shilpa Menghani (Deloitte)
 *      @date         : 08/25/2015
        @description  : MCPM-: Test class for H_DBFunctions.
        Modification Log:
        ------------------------------------------------------------------------------------------
                Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
              Shilpa Menghani (Deloitte)                    08/25/2015            Original Version

*/
@isTest
public  class Test_H_DBFunctions {
    
    static testMethod void testDBFunctionInsert() {
        
        List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(1);
        lstAddress[0].AddressUsageValue__c = 'PRIMARY RESIDENCE';
        Test.startTest();
        
            H_DBFunctions.doInsert(lstAddress, 'H_DBFunctionsTest', 'testDBFunctionInsert', false);          
           
        Test.stopTest();
        
        Integer intCount = Integer.valueOf([Select count(Id) total from Address__c where Id != null][0].get('total'));
        
        System.assertEquals(1, intCount, 'Count didnt match');
     } 
     
     static testMethod void testDBFunctionUpdate() {
        
        String strCountry = 'Canada';
        
        List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(1);
        lstAddress[0].AddressUsageValue__c = 'PRIMARY RESIDENCE';
        
        if(lstAddress != null && !lstAddress.isEmpty())
        insert lstAddress;
        
        for(Address__c objAddress : lstAddress){
            objAddress.CountryValue__c = strCountry;
        }
        
        Test.startTest();
        
            H_DBFunctions.doUpdate(lstAddress, 'H_DBFunctionsTest', 'testDBFunctionUpdate', false);          
           
        Test.stopTest();
        if(lstAddress != null && !lstAddress.isEmpty())
        lstAddress = [SELECT CountryValue__c FROM Address__c WHERE ID IN :lstAddress];
          
        for(Address__c objNewAddress :lstAddress){
            System.assertEquals(objNewAddress.CountryValue__c, strCountry,'Address country name not matching');
         } 
    }  
    
    
    static testMethod void testDBFunctionUpsert() {
       
       
       String strCountry = 'Canada';
        
       List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(1);
       lstAddress[0].AddressUsageValue__c = 'PRIMARY RESIDENCE';
       if(lstAddress != null && !lstAddress.isEmpty())
       insert lstAddress;
        
       lstAddress.addAll(H_ParsingTestDataUtility.createAddress(2));
    
       lstAddress[1].CountryValue__c = strCountry;
       for(Address__c objAddress : lstAddress){
            objAddress.AddressUsageValue__c = 'PRIMARY RESIDENCE';
       }
        
       Test.startTest();
        
          H_DBFunctions.doUpsert(lstAddress, 'H_DBFunctionsTest', 'testDBFunctionUpsert', false);          
           
       Test.stopTest();
       
       if(lstAddress != null && !lstAddress.isEmpty())
       lstAddress = [SELECT CountryValue__c FROM Address__c WHERE ID IN :lstAddress];
         
       System.assertEquals(lstAddress[1].CountryValue__c, strCountry,'Address country name not matching');
        
    }  
    
    static testMethod void testDBFunctionDelete() {
        
       List<Address__c> lstAddress = H_ParsingTestDataUtility.createAddress(2);
       for(Address__c objAddress : lstAddress){
            objAddress.AddressUsageValue__c = 'PRIMARY RESIDENCE';
       }
       if(lstAddress != null && !lstAddress.isEmpty())
       insert lstAddress;
        
        Test.startTest();
        
            H_DBFunctions.doDelete(lstAddress, 'H_DBFunctionsTest', 'testDBFunctionDelete', false);          
           
        Test.stopTest();
            
        try{
            if(lstAddress != null && !lstAddress.isEmpty()){
             lstAddress[1].CountryValue__c ='Canada';
             update lstAddress;
            }
        }
        catch(DmlException e){
            System.assertEquals('ENTITY_IS_DELETED', e.getDmlStatusCode(0),'ENTITY_IS_NOT_DELETED');
        }
             
     } 
    
}