src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>AddressUsageValue__c</fullName>
        <description>Primary residence is brought up to the contact.  All other types are not.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Residence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCOA Address</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>Addr-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UCID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContactMethod__c.object
<CustomObject>
    <fields>
        <fullName>ContactMethodUsageValue__c</fullName>
        <label>Type</label>
        <picklist>
            <controllingField>ContactMethodValue__c</controllingField>
            <picklistValues>
                <fullName>Home Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Primary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Business Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Primary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Business Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evening Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cellular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facsimile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Telephone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Telephone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cellular-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Telephone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Primary Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Business Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Primary Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Business Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evening Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Phone-Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Methods</relationshipLabel>
        <relationshipName>Contact_Method</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Method</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Contact Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Method</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/H_ContacttriggerHelper_test.cls
/**
*      @author       : Piyush Rathor(Deloitte)
*      @date         : 20/12/2015
       @description  : Test class for H_ContacttriggerHelper and H_contacttrigger
        Modification Log:
        ------------------------------------------------------------------------------------------
            Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
          Piyush Rathor                                   20/12/2015         Test class for H_ContacttriggerHelper and H_contacttrigger
          Piyush Rathor                                   05/01/2016         Updation of test class for postal code update
*/    
@istest
public class H_ContacttriggerHelper_test{
    static testMethod void  testContactTrigger(){
        
        //Test account Record
        Account objAccount = H_ParsingTestDataUtility.createAccount(1)[0];
        if(objAccount != null)
            insert objAccount;
        
        system.assertnotEquals(objAccount.Id,null);
        
        //Test Contact Record
        list<Contact>lstContact = H_ParsingTestDataUtility.createContact(1);
        lstContact[0].UCID__c = '3215075397531134';
        lstContact[0].AccountId = objAccount.Id;
        lstContact[0].Phone = '1234567890';
        lstContact[0].Email = 'a@gmail.com';
        lstContact[0].mailingStreet = 'test';
        lstContact[0].MailingCity = 'test';
        lstContact[0].MailingCountry = 'USA';
        if(lstContact != null && !lstContact.isEmpty())
            insert lstContact;
       
        system.assertEquals(lstContact.size(),1);
        
        List<Address__c>lstAddress = H_ParsingTestDataUtility.createAddress(1);
        lstAddress[0].AddressUsageValue__c = H_Constants.addressUsageVal;
        lstAddress[0].Contact__c = lstContact[0].Id;
        lstAddress[0].EndDate__c = system.today() + 10;
        insert lstAddress;
        
        list<ContactMethod__c>lstContactMethod = new list<ContactMethod__c>();
        ContactMethod__c ContactMethod = H_ParsingTestDataUtility.createContactMethod(lstContact[0].Id);
        ContactMethod.ContactMethodUsageValue__c = H_Constants.contactMethodUsageValuePhone;
        lstContactMethod.add(ContactMethod);
        
        ContactMethod__c ContactMethod1 = H_ParsingTestDataUtility.createContactMethod(lstContact[0].Id);
        ContactMethod1.ContactMethodUsageValue__c = H_Constants.contactMethodUsageValue;
        lstContactMethod.add(ContactMethod1);
        insert lstContactMethod;
        
        Test.starttest();
             lstContact[0].firstName = 'testUpdateName';
             lstContact[0].LastName = 'testUpdateLast';
             lstContact[0].MailingPostalCode = '12345';
             update lstContact;
        Test.stopTest();
    }
}