src/objects/Alert__c.object
<CustomObject>
    <description>Alerts tied to a customer</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Alerts</relationshipLabel>
        <relationshipName>Alerts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>When does this alert expire?</description>
        <inlineHelpText>When does this alert expire?</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Alert</label>
    <nameField>
        <label>Alert Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Banner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Max_Value__c</fullName>
        <label>Max Value</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Banner</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Customer or Business Customer</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer, Organization</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>VIN__r.Product_Line__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleValue__c</fullName>
        <label>Role Value</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cobuyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servicer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscriber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrantee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <description>Formula lookup to the UCID.  This is sent in the Workflow outbound message to MDM.</description>
        <formula>Contact__r.UCID__c</formula>
        <label>UCID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Role</label>
    <nameField>
        <displayFormat>Role-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is populated by ODS batch delta loads.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>A   = Honda 
C   = Acura 
M  = Motorcycle 
P  = Power Equipment</description>
        <inlineHelpText>A   = Honda 
C   = Acura 
M  = Motorcycle 
P  = Power Equipment</inlineHelpText>
        <label>Product Line (ODS)</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>Product__r.Product_Line_frontend__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>VIN</relationshipLabel>
        <relationshipName>VIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_CustomerBannerController_test.cls
/**
*      @author       : Piyush Rathor(Deloitte)
*      @date         : 15/10/2015
       @description  : Test class for H_CustomerBannerController4
        Modification Log:
        ------------------------------------------------------------------------------------------
            Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
          Piyush Rathor                                   20/11/2015         Test class for H_CustomerBannerController4
*/    
@istest
public class H_CustomerBannerController_test{
    static testMethod void  testcontactMethodTrigger(){
        //Test account Record
        Account objAccount = H_ParsingTestDataUtility.createAccount(1)[0]; 
        if(objAccount != null)
        insert objAccount;
        system.assertnotEquals(objAccount.Id,null);
        
        //Test Contact Record
        list<Contact>lstContact = H_ParsingTestDataUtility.createContact(1);
        lstContact[0].UCID__c = '3215075397531134';
        lstContact[0].AccountId = objAccount.Id;
        lstContact[0].phone = '1234567890';
        lstContact[0].email = 'test@test.com';
        lstContact[0].mailingstreet = 'test';
        lstContact[0].MailingCity = 'test';
        lstContact[0].MailingCountry = 'USA';
        if(lstContact != null && !lstContact.isEmpty())
        insert lstContact;
        system.assertEquals(lstContact.size(),1);
        
        Banner__c bannerMax = new Banner__c(name = 'gauge',Max_Value__c =100);
        if(bannerMax != null)
        insert bannerMax;
        system.assertnotEquals(bannerMax.Id,null);
        
         Product__c productRecord = H_ParsingTestDataUtility.createProduct();         
        productRecord.Product_Line__c = 'MOTO';
        if(productRecord != null)
        insert productRecord;
        system.assertnotEquals(productRecord.Id,null);    
         
        vin__c vinRecord = H_ParsingTestDataUtility.createVin();
        vinRecord.Product__c = productRecord.Id;
        vinRecord.ProductSerialNumber__c = '1234567899234888';
        if(vinRecord != null)
        insert vinRecord;
        system.assertnotEquals(vinRecord.Id,null);
        
        Customer_Role__c  custRoleRecord = H_ParsingTestDataUtility.createCustomerRole(lstContact[0].Id);        
        custRoleRecord.vin__c = vinRecord.Id;
        custRoleRecord.RoleValue__c = 'Buyer';
        if(custRoleRecord != null)
        insert custRoleRecord;
        system.assertnotEquals(custRoleRecord.Id,null);
        
        Alert__c alert = new Alert__c(Contact__c = lstContact[0].Id,End_Date__c = system.today()+2);
        if(alert != null)
        insert alert;
        system.assertnotEquals(alert.Id,null);
        
        Test.starttest();
            ApexPages.StandardController sc = new ApexPages.StandardController(lstContact[0]);
            H_CustomerBannerController4 customerBanner = new H_CustomerBannerController4(sc);
        Test.stopTest();
    }
}