src/objects/Alert__c.object
<CustomObject>
    <description>Alerts tied to a customer</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Alerts</relationshipLabel>
        <relationshipName>Alerts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>When does this alert expire?</description>
        <inlineHelpText>When does this alert expire?</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Alert</label>
    <nameField>
        <label>Alert Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Banner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Max_Value__c</fullName>
        <label>Max Value</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Banner</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CustomerLoyaltyScore__c</fullName>
        <description>MDM</description>
        <label>Customer Loyalty Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Honda Customer</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Customer or Business Customer</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer, Organization</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EffectiveEndDate__c</fullName>
        <description>MDM</description>
        <label>Effective End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <formula>VIN__r.Product_Line__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleValue__c</fullName>
        <label>Role Value</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cobuyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servicer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscriber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrantee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <description>Formula lookup to the UCID.  This is sent in the Workflow outbound message to MDM.</description>
        <formula>Contact__r.UCID__c</formula>
        <label>UCID</label>
        <type>Text</type>
    </fields>
    <label>Customer Role</label>
    <nameField>
        <displayFormat>Role-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RecallInformations__x.object
<CustomObject>
    <description>RecallInformations</description>
    <externalDataSource>ODS_Data</externalDataSource>
    <externalName>RecallInformations</externalName>
    <fields>
        <fullName>CmpgnTypCd__c</fullName>
        <description>CmpgnTypCd</description>
        <externalDeveloperName>CmpgnTypCd</externalDeveloperName>
        <label>Campaign Type Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MdmUcid__c</fullName>
        <description>MdmUcid</description>
        <externalDeveloperName>MdmUcid</externalDeveloperName>
        <label>Link to Customer</label>
        <length>255</length>
        <referenceTargetField>Contact.UCID__c</referenceTargetField>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recall &amp; Product Update Information</relationshipLabel>
        <relationshipName>RecallInformations</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Recall &amp; Product Update Information</label>
    <pluralLabel>Recall &amp; Product Update Information</pluralLabel>
</CustomObject>

src/classes/H_CustomerBannerController4.cls
/**
*   @author       : Aaron Clancy(Deloitte)
*   @date         : 30/10/2015
    @description  : For showing contact related information on Banner
    Modification Log:
    ------------------------------------------------------------------------------------------
    Developer               User story            Date                Description
    ------------------------------------------------------------------------------------------
    Aaron (Deloitte)                            30/10/2015          Redesigned look based on new business input
    Piyush (Deloitte)                           03/12/2015          Added logic for Recall Information
*/
public with sharing class H_CustomerBannerController4{
    public contact contactRecord{get;set;}                      //Contact record

    // count Customer roles that are ownership ex. owner, lesse
    public Integer hondaActiveCount{get;set;}                   //Count of Active Honda cars 
    public Integer acuraActiveCount{get;set;}                   //Count of Active Acura cars
    public Integer motoActiveCount{get;set;}                    //Count of Active Customer Roles that are motorcycles
    public Integer powerEquipActiveCount{get;set;}              //Count of Active Customer Roles that are power equipment
    
    // count Customer roles that arent ownership ex. Servicer
    public Integer hondaRoleCount{get;set;}                     //Count of Honda cars
    public Integer acuraRoleCount{get;set;}                     //Count of Acura cars
    public Integer motoRoleCount{get;set;}                      //Count of Customer Roles that are motorcycles
    public Integer powerEquipRoleCount{get;set;}                //Count of Customer Roles that are power equipment
    
    public integer maxValue {get;set;}                          //Max Loyalty Score
    public integer activeAlertCount{get;set;}                   //Count of unviewed Alerts
    public integer viewedAlertCount{get;set;}                   //Count of viewed Alerts
    public decimal showStars{get;set;}                          //Stars to show
    private Set<String> activeRoles;                            //List of Active Customer Role names
    
    private STATIC String HONDA = 'C';
    private STATIC String ACURA = 'A';
    private STATIC String MOTO = 'M';
    private STATIC String POWEREQUIP = 'P';
    
    Public Integer recallCount{get;set;}
    Public Integer pudsCount{get;set;}
    
    //Constructor
    public H_CustomerBannerController4(ApexPages.StandardController controller) {
        contactRecord = (contact)controller.getRecord();        //Load contact record on page load
  
        //activeRoles = new Set<String>{'Lesse','Colesse','Buyer','Cobuyer','Owner','Coowner'};
        activeRoles = new Set<String>{'Owner'};

        hondaActiveCount = 0; acuraActiveCount = 0; motoActiveCount = 0; powerEquipActiveCount = 0;
        hondaRoleCount = 0; acuraRoleCount = 0; motoRoleCount = 0; powerEquipRoleCount =0;
        maxValue = 0; activeAlertCount = 0; viewedAlertCount = 0;
        showStars = 0;
        recallCount =0;
        pudsCount=0;
        
        Banner__c bannerMax = Banner__c.getValues('gauge');
        if(bannerMax.Max_Value__c != null){
            maxValue = Integer.valueOf(bannerMax.Max_Value__c);
        }
        
        calculateStars();

        DateTime today = Datetime.now();
        if(contactRecord != null && contactRecord.Id != null){
            for(Customer_Role__c cr : [SELECT Product_Line__c,RoleValue__c,EffectiveEndDate__c FROM Customer_Role__c WHERE Contact__c =: contactRecord.Id]){
                // only active roles
                if(activeRoles.contains(cr.RoleValue__c)){
                    if(cr.EffectiveEndDate__c >= today || cr.EffectiveEndDate__c == null){
                        if(cr.Product_Line__c.equalsIgnoreCase('honda')){ hondaActiveCount++; }
                        else if(cr.Product_Line__c.equalsIgnoreCase('acura')){ acuraActiveCount++; }
                        else if(cr.Product_Line__c.equalsIgnoreCase('moto')){ motoActiveCount++; }
                        else if(cr.Product_Line__c.equalsIgnoreCase('powerequip')){ powerEquipActiveCount++; }
                    }
                }
                // all roles
                if(cr.Product_Line__c.equalsIgnoreCase('honda')){ hondaRoleCount++; }
                else if(cr.Product_Line__c.equalsIgnoreCase('acura')){ acuraRoleCount++; }
                else if(cr.Product_Line__c.equalsIgnoreCase('moto')){ motoRoleCount++; }
                else if(cr.Product_Line__c.equalsIgnoreCase('powerequip')){ powerEquipRoleCount++; }
            }
            
            //Add related Information of Contact in list of contact
            contactRecord = [Select id,CustomerLoyaltyScore__c,UCID__c from contact where Id =: contactRecord.Id];
            for(Alert__c al : [select id,LastViewedDate,CreatedDate from Alert__c where Contact__c =: contactRecord.Id AND (End_Date__c > Today OR End_Date__c = null)]){
                system.debug(' *** ' + al.LastViewedDate +'__'+al.CreatedDate);
                if(al.LastViewedDate != null && al.CreatedDate != null){
                    system.debug(' ***___' +al.LastViewedDate.isSameDay(al.CreatedDate));
                    if(al.LastViewedDate.isSameDay(al.CreatedDate)){
                        activeAlertCount++;
                    }else{
                        viewedAlertCount++;   
                    }
                }
            }
        }
        system.debug(' ***1___'+activeAlertCount+'__'+viewedAlertCount);
        if(contactRecord != null){
        
            list<RecallInformations__x>lstRecall = [Select id,CmpgnTypCd__c from RecallInformations__x where MdmUcid__c =: contactRecord.UCID__c AND (CmpgnTypCd__c = 'R' OR CmpgnTypCd__c = 'U') limit 2000];
            
            if(!lstRecall.isEmpty()){
                for(RecallInformations__x recallInfo : lstRecall){
                    if(recallInfo.CmpgnTypCd__c != null && recallInfo.CmpgnTypCd__c !=''){
                        if(recallInfo.CmpgnTypCd__c == 'R')
                            recallCount++;
                        if(recallInfo.CmpgnTypCd__c == 'U')
                            pudsCount ++;
                    }
                }               
            }  
            
        }
        
    }

    // number of stars to be displayed for this customer
    public void calculateStars() {
        if(contactRecord.CustomerLoyaltyScore__c != null){
             showStars = (contactRecord.CustomerLoyaltyScore__c/maxValue)*5;
         }
    }
}