src/objects/BatchStatus__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Errored</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BatchStatus</label>
    <nameField>
        <label>BatchStatus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BatchStatuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Generate_PINs_Batch_Status__c</fullName>
        <description>The status of the current batch running when creating PINs</description>
        <label>Generate PINs Batch Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Errored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Generated</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/ErrorLog__c.object
<CustomObject>
    <description>Stores the Error Log of the failed records</description>
    <label>ErrorLog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIN__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PIN</relationshipLabel>
        <relationshipName>PIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeemed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PIN</label>
    <nameField>
        <label>PIN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_GeneratePINsBatch.cls
/**
*      @author       : Merisha Shim (Deloitte)
*      @date         : 02/16/3016
*      @description  : Batch Class for the Generate PINs button Campaign
*
*      Modification Log:
*      ------------------------------------------------------------------------------------------
*      Developer               User story            Date                Description
*      ------------------------------------------------------------------------------------------
*      Merisha Shim                                  02/16/3016          Batch Class for the Generate 
*																		 PINs button Campaign
*																																				 Visualforce Page
*/
global class H_GeneratePINsBatch implements Database.Batchable<sObject> {
	
	final String BATCH_NAME = 'Generate PINs Batch';
	final String ACTIVE = 'Active';
	final String IN_PROGRESS = 'In Progress';
	final String COMPLETED = 'Completed';
	final String ERRORED = 'Errored';
	final String DML_OPERATION = 'DML Operation';
	final String PIN = 'PIN__c';

	Integer numberOfPINs;
	Id campaignId;
	Campaign currentCampaign;
	String query;
	
	global H_GeneratePINsBatch(Id camId, Integer pins) {
		numberOfPINs = pins;
		campaignId = camId;
		query = 'Select Id, ContactId, CampaignId FROM CampaignMember WHERE CampaignId =: campaignId';
		currentCampaign = [SELECT Id, Generate_PINS_Batch_Status__c 
							FROM Campaign 
							WHERE Id =: campaignId];
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		
		currentCampaign.Generate_PINS_Batch_Status__c = IN_PROGRESS;

		try {
			// Create an 'In Progress' batch status record
			insert H_GeneratePINs.createBatchStatus(BATCH_NAME, IN_PROGRESS, BC.getJobId());
			update currentCampaign;
		} catch(Exception e) {
			throw new H_GeneratePINs.H_GeneratePINsException(e.getMessage());
		}
		

		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<CampaignMember> scope) {
		
		// Create a map of pin names (the unique pin code) and the PIN record
		Map<String, PIN__c> pinsToInsert = new Map<String, PIN__c>();

		// Set of Contact Ids
		Set<Id> contactIds = new Set<Id>();
		
		// For each Campaign Member, create PINs related to the Contact and Campaign
		for(CampaignMember cm : scope) {
			contactIds.add(cm.ContactId);
			pinsToInsert.putAll(H_GeneratePINs.createPIN(numberOfPins, cm.ContactId, cm.CampaignId, ACTIVE));
		}

		Database.SaveResult[] srList = Database.insert(pinsToInsert.values(), false);

		// Query for all the campaign members in the scope that has less than the number of PINs records
		Map<Id, Contact> contactsWithPINs = new Map<Id, Contact> ([SELECT Id, (SELECT Id FROM PIN__r WHERE Campaign__c =: campaignId)
																		FROM Contact
																		WHERE Id IN: contactIds]);

		List<Contact> contactWithIncorrectPINs = new List<Contact>();

		//go through each contact and make sure the number of pins are correct
		for(Contact c : contactsWithPINs.values()) {
			if(c.PIN__r.size() < numberOfPINs) {
				contactWithIncorrectPINs.add(c);
			}
		}

		if(!contactWithIncorrectPINs.isEmpty() || Test.isRunningTest()) {
			
			List<ErrorLog__c> errorsToInsert = new List<ErrorLog__c>();

			try {
				insert H_GeneratePINs.createErrorLogs(srList, 
														BATCH_NAME, 
														BC.getJobId(), 
														DML_OPERATION, 
														PIN, 
														campaignId, 
														pinsToInsert.values());

			} catch(Exception e) {
				throw new H_GeneratePINs.H_GeneratePINsException(e.getMessage());
			}

			

		}

		
	}
	
	global void finish(Database.BatchableContext BC) {
		// Create a batch status record
		BatchStatus__c batchStatus = H_GeneratePINs.createBatchStatus(BATCH_NAME, COMPLETED, BC.getJobId());
		currentCampaign.Generate_PINS_Batch_Status__c = COMPLETED;
		
		List<ErrorLog__c> dupeErrors = [SELECT Id FROM ErrorLog__c WHERE Name LIKE: '%' + BC.getJobId() + '%'];
		
		if(!dupeErrors.isEmpty()) {
			batchStatus.Status__c = ERRORED;
			currentCampaign.Generate_PINS_Batch_Status__c = ERRORED;
		}

		try {

			insert batchStatus;
			update currentCampaign;

		} catch(Exception e) {
			throw new H_GeneratePINs.H_GeneratePINsException(e.getMessage());
		}
	}

	
}