src/objects/CASS_No__c.object
<CustomObject>
    <fields>
        <fullName>Cass_No__c</fullName>
        <externalId>true</externalId>
        <label>Cass No</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CASS Numbers</relationshipLabel>
        <relationshipName>CASS_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CASS Number</label>
    <nameField>
        <displayFormat>CASS-{00000}</displayFormat>
        <label>CASS Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CASS Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UCID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UCID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Customer_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Customer or Business Customer</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Customer, Organization</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RoleValue__c</fullName>
        <label>Role Value</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cobuyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarantor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servicer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscriber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrantee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UCID__c</fullName>
        <description>Formula lookup to the UCID.  This is sent in the Workflow outbound message to MDM.</description>
        <formula>Contact__r.UCID__c</formula>
        <label>UCID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <referenceTo>VIN__c</referenceTo>
        <relationshipLabel>Customer Roles</relationshipLabel>
        <relationshipName>Customer_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Role</label>
    <nameField>
        <displayFormat>Role-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This is populated by ODS batch delta loads.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <fields>
        <fullName>ProductSerialNumber__c</fullName>
        <externalId>true</externalId>
        <label>VIN/Serial #</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>VIN</relationshipLabel>
        <relationshipName>VIN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_customerRoleTriggerHelper_test.cls
/**
*      @author       : Piyush Rathor(Deloitte)
*      @date         : 01/10/2015
        @description  : Test Class for H_customerRoleTriggerHelper class
        Modification Log:
        ------------------------------------------------------------------------------------------
            Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
           Piyush (Deloitte)                           01/10/2015           Original Version
*/
@istest
public class H_customerRoleTriggerHelper_test{
    //Test method to test scenarios for multi picklist
    static testMethod void  testAutoPopulate(){
        user  userRecordAdmin = H_ParsingTestDataUtility.initUser('System Administrator','test aliasAdmin',null,null);
        if(userRecordAdmin != null)
            insert userRecordAdmin;
        system.assertnotEquals(userRecordAdmin.Id,null);
        
        user  userRecord = H_ParsingTestDataUtility.initUser('API - MDM - Real Time','test alias',null,'CRM Agent');
        system.runas(userRecordAdmin){
            if(userRecord != null)
            insert userRecord;
        }
        system.assertnotEquals(userRecord.Id,null);
        
        //Test account Record
        Account objAccount = H_ParsingTestDataUtility.createAccount(1)[0]; 
        system.runas(userRecord){
            if(objAccount != null)
            insert objAccount;
        }
        system.assertnotEquals(objAccount.Id,null);
        
        //Test Contact Record
        list<Contact>lstContact = H_ParsingTestDataUtility.createContact(1);
        lstContact[0].UCID__c = '3215075310566789';
        lstContact[0].AccountId = objAccount.Id;
        lstContact[0].phone = '1234567890';
        lstContact[0].email = 'test@test.com';
        lstContact[0].mailingstreet = 'test';
        
        if(lstContact != null && !lstContact.isEmpty()){
            system.runas(userRecord){
                insert lstContact;
            }
            system.assertEquals(lstContact.size(),1);
        }
        
        
        Product__c productRecord = H_ParsingTestDataUtility.createProduct();
        system.runas(userRecord){
            if(productRecord != null)
            insert productRecord;
        }
        system.assertnotEquals(productRecord.Id,null);      
        
        vin__c vinRecord = H_ParsingTestDataUtility.createVin();
        vinRecord.Product__c = productRecord.Id;
        vinRecord.ProductSerialNumber__c = '1234567899234888';
        system.runas(userRecord){
            if(vinRecord != null)
            insert vinRecord;
        }
        system.assertnotEquals(vinRecord.Id,null);
        
        vin__c vinRecord1 = H_ParsingTestDataUtility.createVin();
        vinRecord1.Product__c = productRecord.Id;
        vinRecord1.ProductSerialNumber__c = '1234567899234999';
        system.runas(userRecord){
            if(vinRecord1 != null)
            insert vinRecord1;
        }
        system.assertnotEquals(vinRecord1.Id,null);
        
        CASS_No__c cassRecord = new CASS_No__c(contact__c = lstContact[0].Id,Cass_No__c='1234532');
        system.runas(userRecord){
            if(cassRecord != null)
            insert cassRecord;
        }
        system.assertnotEquals(cassRecord.Id,null);
        
        Customer_Role__c  custRoleRecord1 = H_ParsingTestDataUtility.createCustomerRole(lstContact[0].Id);        
        custRoleRecord1.vin__c = vinRecord.Id;
        custRoleRecord1.roleValue__c ='Buyer';
        system.runas(userRecord){
            if(custRoleRecord1 != null)
            insert custRoleRecord1;
        }
        system.assertnotEquals(custRoleRecord1.Id,null);
        
        Customer_Role__c  custRoleRecord = H_ParsingTestDataUtility.createCustomerRole(lstContact[0].Id);        
        custRoleRecord.vin__c = vinRecord.Id;
        Test.startTest();
            system.runas(userRecord){
                if(custRoleRecord != null)
                    insert custRoleRecord;
            }
        system.runas(userRecordAdmin){
            update custRoleRecord;
        }
        Test.stopTest();
    }
}