src/objects/CASS_No__c.object
<CustomObject>
    <fields>
        <fullName>Cass_No__c</fullName>
        <externalId>true</externalId>
        <label>Cass No</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CASS Number</label>
    <nameField>
        <displayFormat>CASS-{00000}</displayFormat>
        <label>CASS Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CASS Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VIN__c.object
<CustomObject>
    <label>VIN/Serial #</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/H_DBFunctions.cls
/**
*      @author Shilpa Menghani
*      @date   22/06/2014
*      @description    A global utility class for all DML Operations
*
*     Modification Log:        
*/

public  class H_DBFunctions{
    
    /**
    *      @author Shilpa Menghani
    *      @date   22/06/2014
    *      @description    Method to pass the failed insert records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.SaveResult> doInsert(List<SObject> insertRecords, String className, String operation,boolean boolAllowPartials){
        List<Database.SaveResult> results= Database.insert(insertRecords,!boolAllowPartials);    
        return results;
    }
    
    
    /**
    *      @author  Shilpa Menghani
    *      @date   22/06/2014
    *      @description    Method to pass the failed Update records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.SaveResult> doUpdate(List<SObject> updateRecords, String className, String operation,boolean boolAllowPartials){
        List<Database.SaveResult> results= Database.update(updateRecords,!boolAllowPartials);
        return results;
    }

    
    /**
    *      @author  Shilpa Menghani
    *      @date    22/06/2014
    *      @description    Method to pass the failed Upsert records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.UpsertResult> doUpsert(List<SObject> upsertRecords, String className, String operation,boolean boolAllowPartials){
        List<Database.Upsertresult> results= Database.upsert(upsertRecords,!boolAllowPartials);
        return results;
    }
    /**
    *      @author  Shilpa Menghani
    *      @date    22/06/2014
    *      @description    Method to pass the failed Upsert records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.UpsertResult> doUpsert(List<Account> upsertRecords, Schema.SObjectField externalIDField,String className, String operation,boolean boolAllowPartials){
        List<Database.Upsertresult> results= Database.upsert(upsertRecords,externalIDField,!boolAllowPartials);
        return results;
    }
     /**
    *      @author  Shilpa Menghani
    *      @date    22/06/2014
    *      @description    Method to pass the failed Upsert records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.UpsertResult> doUpsert(List<Contact> upsertRecords, Schema.SObjectField externalIDField,String className, String operation,boolean boolAllowPartials){
        List<Database.Upsertresult> results= Database.upsert(upsertRecords,externalIDField,!boolAllowPartials);
        return results;
    }
    
    /**
    *      @author  Shilpa Menghani
    *      @date    22/06/2014
    *      @description    Method to pass the failed Upsert records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.UpsertResult> doUpsert(List<CASS_No__c> upsertRecords, Schema.SObjectField externalIDField,String className, String operation,boolean boolAllowPartials){
        List<Database.Upsertresult> results= Database.upsert(upsertRecords,externalIDField,!boolAllowPartials);
        return results;
    }
    
    /**
    *      @author  Shilpa Menghani
    *      @date    22/06/2014
    *      @description    Method to pass the failed Upsert records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.UpsertResult> doUpsert(List<VIN__c> upsertRecords, Schema.SObjectField externalIDField,String className, String operation,boolean boolAllowPartials){
        List<Database.Upsertresult> results= Database.upsert(upsertRecords,externalIDField,!boolAllowPartials);
        return results;
    }
    
    /**
    *      @author  Shilpa Menghani
    *      @date    22/06/2014
    *      @description    Method to pass the failed Delete records for Logger Class
    *      Modification Log:        
    */
    
    public static List<Database.DeleteResult> doDelete(List<SObject> deleteRecords, String className, String operation,boolean boolAllowPartials){
        List<Database.Deleteresult> results= Database.delete(deleteRecords,!boolAllowPartials);
        return results;
  }
}