src/objects/ContactMethod__c.object
<CustomObject>
    <fields>
        <fullName>ContactMethodUsageValue__c</fullName>
        <label>Type</label>
        <picklist>
            <controllingField>ContactMethodValue__c</controllingField>
            <picklistValues>
                <fullName>Home Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Primary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Business Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Primary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Business Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evening Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cellular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facsimile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Telephone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Telephone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cellular-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Telephone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Primary Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Business Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Primary Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Business Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evening Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Phone-Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Phone-Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Methods</relationshipLabel>
        <relationshipName>Contact_Method</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ReferenceNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Method</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Contact Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Method</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/H_Update_Primary_Batch.cls
/**
 *      @author       : Piyush Rathor(Deloitte)
 *      @date         : 10/28/2015
        @description  : This Batch class handles to update contact whenever endDate of contact passes 
        Modification Log:
        ------------------------------------------------------------------------------------------
                Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
                Piyush (Deloitte)                            10/28/2015           Original Version
*/
global with sharing class H_Update_Primary_Batch implements Database.Batchable<SObject>{
     /**        
    * Start method of batch
    */ 
    global Database.querylocator start(Database.BatchableContext BC){
           /**
            * Get list of all Contact Method records whose
            * end date is Today 
            */
            return Database.getQueryLocator([ select Id,
                                                     Contact__c,
                                                     ContactMethodUsageValue__c,
                                                    EndDate__c,
                                                    ReferenceNumber__c
                                              from ContactMethod__c where  EndDate__c =: system.today() AND (ContactMethodUsageValue__c =: H_Constants.contactMethodUsageValuePhone OR ContactMethodUsageValue__c =: H_Constants.contactMethodUsageValue)]);  
    } 
    
    /**        
    * Execute method of batch, delete list of address records.
    */      
    global void execute(Database.BatchableContext BC, List<ContactMethod__c> lstContactMethod){
        try{
            set<Id>setPrimaryEmail = new set<Id>();
            set<Id>setPrimaryPhone = new set<Id>();
            for(ContactMethod__c conMethod : lstContactMethod){
                if(conMethod.ContactMethodUsageValue__c.equalsIgnoreCase(H_Constants.contactMethodUsageValuePhone)){
                    setPrimaryPhone.add(conMethod.Contact__c);
                }
                if(conMethod.ContactMethodUsageValue__c.equalsIgnoreCase(H_Constants.contactMethodUsageValue)){
                    setPrimaryEmail.add(conMethod.Contact__c);
                }
            }
            
            if(!setPrimaryPhone.isEmpty() || !setPrimaryEmail.isEmpty()){
                list<contact>lstCon = [select id,email,phone from contact where Id IN : setPrimaryEmail OR Id IN : setPrimaryPhone];
                if(!lstCon.isEmpty()){
                    for(contact con : lstCon){
                        if(setPrimaryPhone.contains(con.Id))
                            con.phone = null;
                        if(setPrimaryEmail.contains(con.Id))
                            con.email = null;
                    }
                    Database.update(lstCon,false);     
                }
            }
        }
        catch(exception e){
            H_Logger.error(e.getMessage(), 'H_Update_Primary_Batch '+ ' : '+ 'execute','ERROR');
        }       
    }
    
    /**         
    * Finish method of batch 
    */  
    global void finish(Database.BatchableContext BC){ 

    }
}