src/objects/ErrorLog__c.object
<CustomObject>
    <description>Stores the Error Log of the failed records</description>
    <fields>
        <fullName>Message_Short__c</fullName>
        <externalId>true</externalId>
        <label>Message Short</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Stores the message</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <description>Stores the name of the SObject</description>
        <label>SObject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Stores the type of the Operation</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Territory Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DML Operation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webservice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Callouts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Async Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webservice (MDM) - Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webservice (MDM) - Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ErrorLog</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ErrorMessage__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting will hold the error message to be skipped from ErrorLog Batch</description>
    <fields>
        <fullName>MessageShort__c</fullName>
        <label>MessageShort</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ErrorMessage</label>
</CustomObject>

src/classes/H_ErrorLogsBatch_test.cls
/**
 *      @author       : Shilpa Menghani(Deloitte)
 *      @date         : 20/01/2016
        @description  : Test Class for H_ErrH_ErrorLogsBatch class
        Modification Log:
        ------------------------------------------------------------------------------------------
                Developer               User story            Date                Description
        ------------------------------------------------------------------------------------------
              Shilpa(Deloitte)                              20/01/2016           Original Version
*/
@istest
public with sharing class H_ErrorLogsBatch_test {
  static testMethod void  testErrorLogBatch(){
         // Error Message Custom setting data
         ErrorMessage__c errorMsg = new ErrorMessage__c(name = 'Missing', MessageShort__c = 'missing');
         if(errorMsg != null)
         insert errorMsg;
         
         //ErrorLog custom object record
         List<ErrorLog__c> lst_ErrorLog = new  List<ErrorLog__c>();
         ErrorLog__c errorLog1 = new ErrorLog__c();
         errorLog1.Type__c = 'Webservice (MDM) - Inbound';
         errorLog1.SObject__c = 'Contact';
         errorLog1.message__c = 'missing record';
         errorLog1.Message_Short__c = 'missing record';
         lst_ErrorLog.add(errorLog1);
         
         ErrorLog__c errorLog2 = new ErrorLog__c();
         errorLog2.Type__c = 'Webservice (MDM) - Inbound';
         errorLog2.SObject__c = 'Contact';
         errorLog2.Message_Short__c = 'Error - Record Currently Unavailable:';
         errorLog2.Message__c = 'Error - Record Currently Unavailable:';
         lst_ErrorLog.add(errorLog2);
         
         
         Test.startTest(); 
         
	         if(lst_ErrorLog != null && !lst_ErrorLog.isEmpty())
	         insert lst_ErrorLog;
	         
	         String xmlFile = H_ParsingTestDataUtility.getXMLFile();
	         
	         if(lst_ErrorLog != null && lst_ErrorLog.size()> 1)
	         errorLog2 = lst_ErrorLog[1];
	         
	         if(errorLog2 != null && errorLog2.Id != null && String.isNotBlank(xmlFile)){
	           H_logger.saveNotificationXMLAttachment(xmlFile,errorLog2);
	         }
	        
	         H_ErrorLogsBatch errorLogBatch = new H_ErrorLogsBatch();
             String sch = '0 0 23 * * ?'; 
            system.schedule('Test Update', sch, errorLogBatch); 
	     Test.stopTest();   
  }
}